# Import library and split data

In [481]:
import pandas as pd

In [482]:
df = pd.read_csv('../../Data/Blockchain Performance Data/Related2/BPD_related2.csv')
df

Send Rates  Block Size  Avg Latency  Throughput
0          10.0          10         0.32        10.0
1          10.0          20         0.83        10.0
2          10.0          30         1.17         9.9
3          10.0          40         1.16         9.8
4          10.0          50         1.16         9.8
..          ...         ...          ...         ...
395       200.6         160         1.98       159.8
396       200.3         170         2.24       161.0
397       200.5         180         2.09       161.8
398       200.3         190         2.24       160.4
399       200.1         200         1.67       160.8

[400 rows x 4 columns]

In [483]:
xy = df.values
xy

array([[ 10.  ,  10.  ,   0.32,  10.  ],
       [ 10.  ,  20.  ,   0.83,  10.  ],
       [ 10.  ,  30.  ,   1.17,   9.9 ],
       ...,
       [200.5 , 180.  ,   2.09, 161.8 ],
       [200.3 , 190.  ,   2.24, 160.4 ],
       [200.1 , 200.  ,   1.67, 160.8 ]])

In [484]:
import torch
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [485]:
# set random seed
seed = 42
torch.manual_seed(seed)

In [486]:
# Read raw data and divide training set and test set
raw_data = xy
X = raw_data[:, :2]
Y1 = raw_data[:, -2:-1]
Y2 = raw_data[:, -1:]

In [487]:
X

array([[ 10. ,  10. ],
       [ 10. ,  20. ],
       [ 10. ,  30. ],
       [ 10. ,  40. ],
       [ 10. ,  50. ],
       [ 10. ,  60. ],
       [ 10. ,  70. ],
       [ 10. ,  80. ],
       [ 10. ,  90. ],
       [ 10. , 100. ],
       [ 10. , 110. ],
       [ 10. , 120. ],
       [ 10.1, 130. ],
       [ 10. , 140. ],
       [ 10. , 150. ],
       [ 10. , 160. ],
       [ 10. , 170. ],
       [ 10. , 180. ],
       [ 10. , 190. ],
       [ 10. , 200. ],
       [ 20.1,  10. ],
       [ 20.1,  20. ],
       [ 20.1,  30. ],
       [ 20.1,  40. ],
       [ 20.1,  50. ],
       [ 20.1,  60. ],
       [ 20.1,  70. ],
       [ 20.1,  80. ],
       [ 20.1,  90. ],
       [ 20.1, 100. ],
       [ 20.1, 110. ],
       [ 20.1, 120. ],
       [ 20.1, 130. ],
       [ 20.1, 140. ],
       [ 20.1, 150. ],
       [ 20.1, 160. ],
       [ 20.1, 170. ],
       [ 20.1, 180. ],
       [ 20.1, 190. ],
       [ 20.1, 200. ],
       [ 30.1,  10. ],
       [ 30.1,  20. ],
       [ 30.1,  30. ],
       [ 30

In [488]:
Y1

array([[0.32],
       [0.83],
       [1.17],
       [1.16],
       [1.16],
       [1.15],
       [1.13],
       [1.2 ],
       [1.16],
       [1.14],
       [1.15],
       [1.17],
       [1.2 ],
       [1.18],
       [1.16],
       [1.17],
       [1.19],
       [1.17],
       [1.18],
       [1.18],
       [0.19],
       [0.46],
       [0.72],
       [0.98],
       [1.17],
       [1.17],
       [1.15],
       [1.14],
       [1.16],
       [1.16],
       [1.14],
       [1.16],
       [1.18],
       [1.18],
       [1.15],
       [1.18],
       [1.16],
       [1.19],
       [1.18],
       [1.19],
       [0.14],
       [0.31],
       [0.51],
       [0.67],
       [0.85],
       [1.05],
       [1.14],
       [1.15],
       [1.16],
       [1.13],
       [1.16],
       [1.17],
       [1.18],
       [1.16],
       [1.15],
       [1.16],
       [1.16],
       [1.17],
       [1.16],
       [1.15],
       [0.11],
       [0.24],
       [0.39],
       [0.51],
       [0.67],
       [0.83],
       [0.

In [489]:
Y2

array([[ 10. ],
       [ 10. ],
       [  9.9],
       [  9.8],
       [  9.8],
       [ 10. ],
       [ 10. ],
       [  9.9],
       [  9.8],
       [ 10. ],
       [  9.8],
       [  9.8],
       [  9.9],
       [  9.9],
       [  9.8],
       [  9.9],
       [  9.9],
       [  9.9],
       [  9.9],
       [  9.8],
       [ 20.1],
       [ 20.1],
       [ 19.4],
       [ 20.1],
       [ 20.1],
       [ 20. ],
       [ 20. ],
       [ 20. ],
       [ 19.9],
       [ 20. ],
       [ 19.4],
       [ 19.3],
       [ 19.3],
       [ 19.8],
       [ 19.3],
       [ 19.8],
       [ 19.9],
       [ 19.8],
       [ 19.8],
       [ 19.8],
       [ 30.1],
       [ 30.1],
       [ 28.5],
       [ 30.1],
       [ 30.1],
       [ 29.3],
       [ 28.6],
       [ 28.6],
       [ 28.8],
       [ 28.7],
       [ 28.8],
       [ 28.5],
       [ 28.6],
       [ 28.7],
       [ 28.6],
       [ 28.5],
       [ 28.6],
       [ 28.7],
       [ 28.5],
       [ 28.6],
       [ 40.1],
       [ 40.1],
       [

# MLP1(send rates, block size) = latency

In [490]:
# Split training set and test set
Xtrain1, Xtest1, Ytrain1, Ytest1 = train_test_split(X, Y1, test_size=0.2, random_state=1)

In [491]:
# test set
Xtest1

array([[200.3, 190. ],
       [ 70.3,  60. ],
       [170.5,  90. ],
       [170.8, 200. ],
       [ 90.4, 130. ],
       [180.4,  30. ],
       [100.5, 180. ],
       [150.4, 120. ],
       [ 20.1, 100. ],
       [150.3,  50. ],
       [ 90.4, 150. ],
       [187.4, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [170.5,  20. ],
       [120.4,  80. ],
       [189.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.5,  30. ],
       [200.4,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.8,  70. ],
       [110.5,  20. ],
       [190.4,  20. ],
       [110.4,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.6, 160. ],
       [ 10. ,  70. ],
       [ 50.3,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [200.5, 180. ],
       [ 70.3, 200. ],
       [140.3,  90. ],
       [110.4,  50. ],
       [ 90.3, 120. ],
       [ 40

In [492]:
Ytest1

array([[2.24],
       [0.56],
       [0.6 ],
       [0.89],
       [0.88],
       [1.96],
       [0.75],
       [0.94],
       [1.16],
       [0.51],
       [0.89],
       [2.76],
       [0.63],
       [1.85],
       [1.11],
       [0.59],
       [2.19],
       [1.15],
       [1.16],
       [0.34],
       [0.26],
       [0.24],
       [2.19],
       [0.86],
       [1.17],
       [1.23],
       [1.46],
       [0.15],
       [1.95],
       [0.61],
       [0.2 ],
       [1.16],
       [0.48],
       [0.79],
       [1.13],
       [0.1 ],
       [1.16],
       [0.29],
       [2.09],
       [1.04],
       [0.57],
       [0.34],
       [0.96],
       [0.39],
       [2.13],
       [0.7 ],
       [1.95],
       [0.61],
       [0.9 ],
       [0.8 ],
       [0.83],
       [0.45],
       [0.63],
       [1.18],
       [0.84],
       [0.52],
       [1.97],
       [1.22],
       [0.85],
       [2.44],
       [0.8 ],
       [1.08],
       [0.83],
       [0.51],
       [1.35],
       [0.26],
       [0.

In [493]:
# property scaling
min_max_scaler1 = preprocessing.MinMaxScaler()

In [494]:
# Scaling training set data
Xtrain1_minmax = min_max_scaler1.fit_transform(Xtrain1)
Xtrain1_minmax

array([[2.10691824e-01, 6.84210526e-01],
       [5.29350105e-02, 1.57894737e-01],
       [7.36897275e-01, 1.00000000e+00],
       [0.00000000e+00, 6.84210526e-01],
       [2.10691824e-01, 5.26315789e-01],
       [1.58280922e-01, 5.26315789e-02],
       [9.95283019e-01, 5.26315789e-02],
       [5.26205451e-01, 6.84210526e-01],
       [9.94758910e-01, 5.78947368e-01],
       [3.16037736e-01, 3.68421053e-01],
       [3.68448637e-01, 1.00000000e+00],
       [8.93605870e-01, 7.89473684e-01],
       [7.36373166e-01, 1.57894737e-01],
       [8.41194969e-01, 9.47368421e-01],
       [4.21383648e-01, 5.26315789e-02],
       [7.89308176e-01, 0.00000000e+00],
       [6.83962264e-01, 8.94736842e-01],
       [7.35324948e-01, 4.73684211e-01],
       [6.83962264e-01, 0.00000000e+00],
       [4.21383648e-01, 6.84210526e-01],
       [2.10691824e-01, 1.05263158e-01],
       [9.47064990e-01, 3.68421053e-01],
       [4.21383648e-01, 1.00000000e+00],
       [5.29350105e-02, 3.68421053e-01],
       [2.106918

In [495]:
# Apply the same scaling to the test set data
Xtest1_minmax = min_max_scaler1.transform(Xtest1)
Xtest1_minmax

array([[0.99737945, 0.94736842],
       [0.31603774, 0.26315789],
       [0.84119497, 0.42105263],
       [0.8427673 , 1.        ],
       [0.42138365, 0.63157895],
       [0.89308176, 0.10526316],
       [0.47431866, 0.89473684],
       [0.73584906, 0.57894737],
       [0.05293501, 0.47368421],
       [0.73532495, 0.21052632],
       [0.42138365, 0.73684211],
       [0.92976939, 0.63157895],
       [0.47379455, 0.42105263],
       [0.84171908, 0.21052632],
       [0.84119497, 0.05263158],
       [0.57861635, 0.36842105],
       [0.94077568, 0.57894737],
       [0.        , 0.26315789],
       [0.15828092, 0.94736842],
       [0.57861635, 0.15789474],
       [0.31656184, 0.10526316],
       [0.63155136, 0.10526316],
       [0.99790356, 0.10526316],
       [0.52672956, 0.73684211],
       [0.        , 0.89473684],
       [0.21069182, 0.63157895],
       [0.9475891 , 0.31578947],
       [0.52672956, 0.05263158],
       [0.94549266, 0.05263158],
       [0.52620545, 0.36842105],
       [0.

In [496]:
Xtest1_tensor = torch.from_numpy(Xtest1_minmax).type(torch.float32)
Ytest1_tensor = torch.from_numpy(Ytest1).type(torch.float32)

In [497]:
Xtest1_tensor

tensor([[0.9974, 0.9474],
        [0.3160, 0.2632],
        [0.8412, 0.4211],
        [0.8428, 1.0000],
        [0.4214, 0.6316],
        [0.8931, 0.1053],
        [0.4743, 0.8947],
        [0.7358, 0.5789],
        [0.0529, 0.4737],
        [0.7353, 0.2105],
        [0.4214, 0.7368],
        [0.9298, 0.6316],
        [0.4738, 0.4211],
        [0.8417, 0.2105],
        [0.8412, 0.0526],
        [0.5786, 0.3684],
        [0.9408, 0.5789],
        [0.0000, 0.2632],
        [0.1583, 0.9474],
        [0.5786, 0.1579],
        [0.3166, 0.1053],
        [0.6316, 0.1053],
        [0.9979, 0.1053],
        [0.5267, 0.7368],
        [0.0000, 0.8947],
        [0.2107, 0.6316],
        [0.9476, 0.3158],
        [0.5267, 0.0526],
        [0.9455, 0.0526],
        [0.5262, 0.3684],
        [0.2107, 0.0526],
        [0.0000, 0.2105],
        [0.4214, 0.2632],
        [0.6845, 0.7895],
        [0.0000, 0.3158],
        [0.2112, 0.0000],
        [0.1053, 0.9474],
        [0.2636, 0.1053],
        [0.9

In [498]:
# batch the training dataset
# prepare dataset
class BlockChainDataset(Dataset):
    def __init__(self, data, label):
        self.len = data.shape[0]
        self.x_data = torch.from_numpy(data).type(torch.float32)
        self.y_data = torch.from_numpy(label).type(torch.float32)
        
        
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len

In [499]:
train_dataset = BlockChainDataset(Xtrain1_minmax, Ytrain1)
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=False)

In [500]:
import torch.nn as nn
import torch.optim as optim

In [501]:
# design model using class
class Lat(torch.nn.Module):
    def __init__(self):
        super(Lat, self).__init__()
        self.fc1 = nn.Linear(2, 64)
        self.fc2 = nn.Linear(64, 8)
        self.relu = nn.ReLU()
        self.fc3 = nn.Linear(8, 1)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out
    
    
model = Lat()

In [502]:
# net = nn.Sequential(
#     nn.Linear(2, 64), nn.BatchNorm1d(64), nn.Dropout(p=0.5), nn.ReLU(),
#     nn.Linear(64, 64), nn.BatchNorm1d(64), nn.Dropout(p=0.5), nn.ReLU(),
#     nn.Linear(64, 1))


# model = net

In [503]:
# construct loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [504]:
# traning cycle forward, backward, update
def train(epoch):
    train_loss = 0.0
    for batch_idx, (inputs, labels) in enumerate(train_loader, 0):
        y_pred = model(inputs)
        loss = criterion(y_pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * labels.shape[0]
    if (epoch + 1) % 10 == 0:
        print('epoch:', epoch + 1, 'train_loss:', train_loss / len(Xtrain1))
        

def test():
    with torch.no_grad():
        y_pred = model(Xtest1_tensor)
        loss = criterion(y_pred, Ytest1_tensor)
        print('test_loss:', loss)

In [505]:
if __name__ == '__main__':
    for epoch in range(5000):
        train(epoch)
        if (epoch + 1) % 10 == 0:
            model.eval()
            test()

epoch: 10 train_loss: 0.5356724679470062
test_loss: tensor(0.4539)
epoch: 20 train_loss: 0.2824483647942543
test_loss: tensor(0.3305)
epoch: 30 train_loss: 0.25690845474600793
test_loss: tensor(0.2867)
epoch: 40 train_loss: 0.23618261143565178
test_loss: tensor(0.2552)
epoch: 50 train_loss: 0.2169844914227724
test_loss: tensor(0.2272)
epoch: 60 train_loss: 0.20021689161658288
test_loss: tensor(0.2013)
epoch: 70 train_loss: 0.185865543410182
test_loss: tensor(0.1781)
epoch: 80 train_loss: 0.17630511689931155
test_loss: tensor(0.1636)
epoch: 90 train_loss: 0.16901336200535297
test_loss: tensor(0.1531)
epoch: 100 train_loss: 0.16385043766349555
test_loss: tensor(0.1449)
epoch: 110 train_loss: 0.15983230732381343
test_loss: tensor(0.1395)
epoch: 120 train_loss: 0.1561329485848546
test_loss: tensor(0.1355)
epoch: 130 train_loss: 0.1535525530576706
test_loss: tensor(0.1318)
epoch: 140 train_loss: 0.15095491241663694
test_loss: tensor(0.1290)
epoch: 150 train_loss: 0.14836683869361877
test_lo

epoch: 1240 train_loss: 0.07255258578807115
test_loss: tensor(0.0720)
epoch: 1250 train_loss: 0.07226672917604446
test_loss: tensor(0.0719)
epoch: 1260 train_loss: 0.07179428841918707
test_loss: tensor(0.0713)
epoch: 1270 train_loss: 0.07107398863881827
test_loss: tensor(0.0708)
epoch: 1280 train_loss: 0.07009069789201021
test_loss: tensor(0.0718)
epoch: 1290 train_loss: 0.06914196833968163
test_loss: tensor(0.0717)
epoch: 1300 train_loss: 0.06987595530226827
test_loss: tensor(0.0704)
epoch: 1310 train_loss: 0.06841354444622993
test_loss: tensor(0.0704)
epoch: 1320 train_loss: 0.0677766352891922
test_loss: tensor(0.0713)
epoch: 1330 train_loss: 0.06750698816031217
test_loss: tensor(0.0702)
epoch: 1340 train_loss: 0.06673963032662869
test_loss: tensor(0.0696)
epoch: 1350 train_loss: 0.0660853374749422
test_loss: tensor(0.0691)
epoch: 1360 train_loss: 0.06539254859089852
test_loss: tensor(0.0690)
epoch: 1370 train_loss: 0.06473603155463933
test_loss: tensor(0.0704)
epoch: 1380 train_loss

epoch: 2410 train_loss: 0.0363330396823585
test_loss: tensor(0.0729)
epoch: 2420 train_loss: 0.03619685899466276
test_loss: tensor(0.0731)
epoch: 2430 train_loss: 0.03610148578882218
test_loss: tensor(0.0733)
epoch: 2440 train_loss: 0.03575589880347252
test_loss: tensor(0.0748)
epoch: 2450 train_loss: 0.03574626659974456
test_loss: tensor(0.0749)
epoch: 2460 train_loss: 0.03573888586834073
test_loss: tensor(0.0741)
epoch: 2470 train_loss: 0.03552989261224866
test_loss: tensor(0.0754)
epoch: 2480 train_loss: 0.03555028866976499
test_loss: tensor(0.0745)
epoch: 2490 train_loss: 0.03547710301354527
test_loss: tensor(0.0758)
epoch: 2500 train_loss: 0.03545870874077082
test_loss: tensor(0.0752)
epoch: 2510 train_loss: 0.03533180225640535
test_loss: tensor(0.0762)
epoch: 2520 train_loss: 0.03528259126469493
test_loss: tensor(0.0757)
epoch: 2530 train_loss: 0.0350589825771749
test_loss: tensor(0.0769)
epoch: 2540 train_loss: 0.03514918079599738
test_loss: tensor(0.0762)
epoch: 2550 train_loss

epoch: 3620 train_loss: 0.032641019020229575
test_loss: tensor(0.0821)
epoch: 3630 train_loss: 0.032591269072145226
test_loss: tensor(0.0823)
epoch: 3640 train_loss: 0.03262493833899498
test_loss: tensor(0.0822)
epoch: 3650 train_loss: 0.03249411350116134
test_loss: tensor(0.0827)
epoch: 3660 train_loss: 0.032597544323652985
test_loss: tensor(0.0827)
epoch: 3670 train_loss: 0.03253252673894167
test_loss: tensor(0.0829)
epoch: 3680 train_loss: 0.032563259406015274
test_loss: tensor(0.0832)
epoch: 3690 train_loss: 0.032523590791970494
test_loss: tensor(0.0831)
epoch: 3700 train_loss: 0.032439693063497546
test_loss: tensor(0.0832)
epoch: 3710 train_loss: 0.03244939628057182
test_loss: tensor(0.0838)
epoch: 3720 train_loss: 0.03252181666903198
test_loss: tensor(0.0835)
epoch: 3730 train_loss: 0.03247583108022809
test_loss: tensor(0.0838)
epoch: 3740 train_loss: 0.03243313087150455
test_loss: tensor(0.0845)
epoch: 3750 train_loss: 0.0324551947414875
test_loss: tensor(0.0840)
epoch: 3760 tra

epoch: 4810 train_loss: 0.030553335230797528
test_loss: tensor(0.0852)
epoch: 4820 train_loss: 0.030588829796761273
test_loss: tensor(0.0864)
epoch: 4830 train_loss: 0.030447599943727255
test_loss: tensor(0.0856)
epoch: 4840 train_loss: 0.030316462507471442
test_loss: tensor(0.0843)
epoch: 4850 train_loss: 0.03037012042477727
test_loss: tensor(0.0839)
epoch: 4860 train_loss: 0.030334006249904632
test_loss: tensor(0.0844)
epoch: 4870 train_loss: 0.03028603093698621
test_loss: tensor(0.0833)
epoch: 4880 train_loss: 0.030462692538276315
test_loss: tensor(0.0822)
epoch: 4890 train_loss: 0.030434750113636257
test_loss: tensor(0.0827)
epoch: 4900 train_loss: 0.03047038852237165
test_loss: tensor(0.0830)
epoch: 4910 train_loss: 0.030521745420992376
test_loss: tensor(0.0831)
epoch: 4920 train_loss: 0.03055404624901712
test_loss: tensor(0.0824)
epoch: 4930 train_loss: 0.030656213825568556
test_loss: tensor(0.0821)
epoch: 4940 train_loss: 0.030648046266287567
test_loss: tensor(0.0817)
epoch: 495

In [506]:
Xtest1

array([[200.3, 190. ],
       [ 70.3,  60. ],
       [170.5,  90. ],
       [170.8, 200. ],
       [ 90.4, 130. ],
       [180.4,  30. ],
       [100.5, 180. ],
       [150.4, 120. ],
       [ 20.1, 100. ],
       [150.3,  50. ],
       [ 90.4, 150. ],
       [187.4, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [170.5,  20. ],
       [120.4,  80. ],
       [189.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.5,  30. ],
       [200.4,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.8,  70. ],
       [110.5,  20. ],
       [190.4,  20. ],
       [110.4,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.6, 160. ],
       [ 10. ,  70. ],
       [ 50.3,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [200.5, 180. ],
       [ 70.3, 200. ],
       [140.3,  90. ],
       [110.4,  50. ],
       [ 90.3, 120. ],
       [ 40

In [507]:
Xtest1[:, 1].reshape(-1)

array([190.,  60.,  90., 200., 130.,  30., 180., 120., 100.,  50., 150.,
       130.,  90.,  50.,  20.,  80., 120.,  60., 190.,  40.,  30.,  30.,
        30., 150., 180., 130.,  70.,  20.,  20.,  80.,  20.,  50.,  60.,
       160.,  70.,  10., 190.,  30., 180., 200.,  90.,  50., 120.,  30.,
        60.,  60., 100.,  80., 150., 190.,  60.,  60., 100., 190., 170.,
        70., 130., 180., 190.,  10.,  80.,  80., 150.,  70., 150.,  30.,
        70., 110., 110., 130., 190., 160., 110.,  80., 120.,  80.,  20.,
        10., 130.,  50.])

In [508]:
with torch.no_grad():
    y_pred = model(Xtest1_tensor)
y = pd.concat([pd.Series(Xtest1[:, 0].reshape(-1), name='send rates'), pd.Series(Xtest1[:, 1].reshape(-1), name='block size'), 
               pd.Series(Ytest1_tensor.numpy().reshape(-1), name='latency_true'), pd.Series(y_pred.numpy().reshape(-1), name='latency_pred')], 
              axis=1)
y.to_csv('../../Data/Blockchain Performance Data/Related2/latency_true_pred_related2.csv')

In [509]:
# Compute test set MAE RMSE MAPE
import pandas as pd

data = pd.read_csv('../../Data/Blockchain Performance Data/Related2/latency_true_pred_related2.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

send rates  block size  latency_true  latency_pred
0       200.3       190.0          2.24      1.857433
1        70.3        60.0          0.56      0.549940
2       170.5        90.0          0.60      0.776314
3       170.8       200.0          0.89      0.969467
4        90.4       130.0          0.88      1.816091

In [510]:
y = data['latency_true'].values
y

array([2.24, 0.56, 0.6 , 0.89, 0.88, 1.96, 0.75, 0.94, 1.16, 0.51, 0.89,
       2.76, 0.63, 1.85, 1.11, 0.59, 2.19, 1.15, 1.16, 0.34, 0.26, 0.24,
       2.19, 0.86, 1.17, 1.23, 1.46, 0.15, 1.95, 0.61, 0.2 , 1.16, 0.48,
       0.79, 1.13, 0.1 , 1.16, 0.29, 2.09, 1.04, 0.57, 0.34, 0.96, 0.39,
       2.13, 0.7 , 1.95, 0.61, 0.9 , 0.8 , 0.83, 0.45, 0.63, 1.18, 0.84,
       0.52, 1.97, 1.22, 0.85, 2.44, 0.8 , 1.08, 0.83, 0.51, 1.35, 0.26,
       0.7 , 0.91, 0.71, 3.38, 0.86, 1.2 , 1.8 , 2.03, 1.17, 0.95, 0.31,
       0.07, 1.12, 0.33])

In [511]:
y_hat = data['latency_pred'].values
y_hat

array([1.8574334 , 0.5499399 , 0.776314  , 0.96946704, 1.8160906 ,
       1.4750938 , 0.8048068 , 0.94238436, 1.1501248 , 0.33670908,
       0.8707404 , 3.4853857 , 0.581505  , 0.795436  , 1.1514668 ,
       0.51750207, 1.8868225 , 1.3739729 , 1.1518406 , 0.27108598,
       0.23030351, 0.24180092, 1.9468338 , 0.7751869 , 1.1854663 ,
       1.2889298 , 1.5041304 , 0.1164472 , 1.8081096 , 0.5174047 ,
       0.2255715 , 1.2364568 , 0.39818364, 0.78869736, 1.4553789 ,
       0.10079069, 1.1575614 , 0.26992542, 1.9093457 , 1.0647382 ,
       0.5075893 , 0.3295058 , 0.9033133 , 0.40153283, 2.0163171 ,
       0.7296915 , 1.954634  , 0.53325486, 0.8920676 , 0.73490965,
       0.84941876, 0.39261204, 0.645897  , 1.1821983 , 0.71439195,
       0.39326698, 3.3023312 , 1.1210142 , 0.78458023, 2.485604  ,
       0.8020888 , 0.9977536 , 0.81241214, 0.45691252, 1.2409756 ,
       0.21536376, 0.7199755 , 0.83972436, 0.7117578 , 3.2692378 ,
       0.7693788 , 1.1620295 , 1.2664062 , 1.0404849 , 1.16970

In [512]:
from sklearn import metrics

In [514]:
MAE = metrics.mean_absolute_error(y, y_hat)
RMSE = metrics.mean_squared_error(y, y_hat) ** 0.5
MAPE = metrics.mean_absolute_percentage_error(y, y_hat)
print('MAE: ', MAE)
print('RMSE: ', RMSE)
print('MAPE: ', MAPE)

MAE:  0.1394217845825
RMSE:  0.2867707738390911
MAPE:  0.1299774027874181


# MLP2(send rates, block size) = throughput

In [515]:
# Split training set and test set
Xtrain2, Xtest2, Ytrain2, Ytest2 = train_test_split(X, Y2, test_size=0.2, random_state=1)

In [516]:
Xtest2

array([[200.3, 190. ],
       [ 70.3,  60. ],
       [170.5,  90. ],
       [170.8, 200. ],
       [ 90.4, 130. ],
       [180.4,  30. ],
       [100.5, 180. ],
       [150.4, 120. ],
       [ 20.1, 100. ],
       [150.3,  50. ],
       [ 90.4, 150. ],
       [187.4, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [170.5,  20. ],
       [120.4,  80. ],
       [189.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.5,  30. ],
       [200.4,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.8,  70. ],
       [110.5,  20. ],
       [190.4,  20. ],
       [110.4,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.6, 160. ],
       [ 10. ,  70. ],
       [ 50.3,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [200.5, 180. ],
       [ 70.3, 200. ],
       [140.3,  90. ],
       [110.4,  50. ],
       [ 90.3, 120. ],
       [ 40

In [517]:
Ytest2

array([[160.4],
       [ 63.2],
       [127. ],
       [159.6],
       [ 80.2],
       [127.6],
       [ 97.1],
       [117.4],
       [ 20. ],
       [118.3],
       [ 81. ],
       [149.7],
       [ 83.6],
       [126.4],
       [124.6],
       [ 99.2],
       [132.7],
       [ 10. ],
       [ 37.6],
       [119.4],
       [ 61.7],
       [103.2],
       [134.7],
       [ 96.7],
       [  9.9],
       [ 48. ],
       [133.6],
       [110. ],
       [132.9],
       [ 92.5],
       [ 50.1],
       [  9.8],
       [ 78.3],
       [121.6],
       [ 10. ],
       [ 50.2],
       [ 28.5],
       [ 53.9],
       [161.8],
       [ 61.5],
       [109.6],
       [109.5],
       [ 78.4],
       [ 37.3],
       [134.8],
       [ 46.9],
       [142.9],
       [123.8],
       [121.3],
       [122. ],
       [ 38.3],
       [ 98.9],
       [118.8],
       [  9.9],
       [121. ],
       [116.2],
       [117.5],
       [ 54.5],
       [120.1],
       [131.4],
       [ 55.2],
       [ 38.3],
       [

In [518]:
# property scaling
min_max_scaler2 = preprocessing.MinMaxScaler()

In [519]:
# Scaling training set data
Xtrain2_minmax = min_max_scaler2.fit_transform(Xtrain2)
Xtrain2_minmax

array([[2.10691824e-01, 6.84210526e-01],
       [5.29350105e-02, 1.57894737e-01],
       [7.36897275e-01, 1.00000000e+00],
       [0.00000000e+00, 6.84210526e-01],
       [2.10691824e-01, 5.26315789e-01],
       [1.58280922e-01, 5.26315789e-02],
       [9.95283019e-01, 5.26315789e-02],
       [5.26205451e-01, 6.84210526e-01],
       [9.94758910e-01, 5.78947368e-01],
       [3.16037736e-01, 3.68421053e-01],
       [3.68448637e-01, 1.00000000e+00],
       [8.93605870e-01, 7.89473684e-01],
       [7.36373166e-01, 1.57894737e-01],
       [8.41194969e-01, 9.47368421e-01],
       [4.21383648e-01, 5.26315789e-02],
       [7.89308176e-01, 0.00000000e+00],
       [6.83962264e-01, 8.94736842e-01],
       [7.35324948e-01, 4.73684211e-01],
       [6.83962264e-01, 0.00000000e+00],
       [4.21383648e-01, 6.84210526e-01],
       [2.10691824e-01, 1.05263158e-01],
       [9.47064990e-01, 3.68421053e-01],
       [4.21383648e-01, 1.00000000e+00],
       [5.29350105e-02, 3.68421053e-01],
       [2.106918

In [520]:
# Apply the same scaling to the test set data
Xtest2_minmax = min_max_scaler2.transform(Xtest2)
Xtest2_minmax

array([[0.99737945, 0.94736842],
       [0.31603774, 0.26315789],
       [0.84119497, 0.42105263],
       [0.8427673 , 1.        ],
       [0.42138365, 0.63157895],
       [0.89308176, 0.10526316],
       [0.47431866, 0.89473684],
       [0.73584906, 0.57894737],
       [0.05293501, 0.47368421],
       [0.73532495, 0.21052632],
       [0.42138365, 0.73684211],
       [0.92976939, 0.63157895],
       [0.47379455, 0.42105263],
       [0.84171908, 0.21052632],
       [0.84119497, 0.05263158],
       [0.57861635, 0.36842105],
       [0.94077568, 0.57894737],
       [0.        , 0.26315789],
       [0.15828092, 0.94736842],
       [0.57861635, 0.15789474],
       [0.31656184, 0.10526316],
       [0.63155136, 0.10526316],
       [0.99790356, 0.10526316],
       [0.52672956, 0.73684211],
       [0.        , 0.89473684],
       [0.21069182, 0.63157895],
       [0.9475891 , 0.31578947],
       [0.52672956, 0.05263158],
       [0.94549266, 0.05263158],
       [0.52620545, 0.36842105],
       [0.

In [521]:
Xtest2_tensor = torch.from_numpy(Xtest2_minmax).type(torch.float32)
Ytest2_tensor = torch.from_numpy(Ytest2).type(torch.float32)

In [522]:
train_dataset = BlockChainDataset(Xtrain2_minmax, Ytrain2)
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=False)

In [523]:
# design model using class
class Thr(torch.nn.Module):
    def __init__(self):
        super(Thr, self).__init__()
        self.fc1 = nn.Linear(2, 64)
        self.fc2 = nn.Linear(64, 8)
        self.relu = nn.ReLU()
        self.fc3 = nn.Linear(8, 1)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out
    
    
model1 = Thr()

In [524]:
# construct loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model1.parameters(), lr=0.001)

In [525]:
# traning cycle forward, backward, update
def train1(epoch):
    train_loss = 0.0
    for batch_idx, (inputs, labels) in enumerate(train_loader, 0):
        y_pred = model1(inputs)
        loss = criterion(y_pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * labels.shape[0]
    if (epoch + 1) % 10 == 0:
        print('epoch:', epoch + 1, 'train_loss:', train_loss / len(Xtrain2))
        

def test1():
    with torch.no_grad():
        y_pred = model1(Xtest2_tensor)
        loss = criterion(y_pred, Ytest2_tensor)
        print('test_loss:', loss)

In [533]:
if __name__ == '__main__':
    for epoch in range(1000):
        train1(epoch)
        if (epoch + 1) % 10 == 0:
            model1.eval()
            test1()

epoch: 10 train_loss: 78.70950431823731
test_loss: tensor(84.9434)
epoch: 20 train_loss: 78.61490135192871
test_loss: tensor(84.8328)
epoch: 30 train_loss: 78.52096633911133
test_loss: tensor(84.7116)
epoch: 40 train_loss: 78.43029136657715
test_loss: tensor(84.5847)
epoch: 50 train_loss: 78.34125747680665
test_loss: tensor(84.4466)
epoch: 60 train_loss: 78.25156936645507
test_loss: tensor(84.3031)
epoch: 70 train_loss: 78.17015495300294
test_loss: tensor(84.1954)
epoch: 80 train_loss: 78.08924255371093
test_loss: tensor(84.0972)
epoch: 90 train_loss: 78.01140441894532
test_loss: tensor(83.9934)
epoch: 100 train_loss: 77.93521423339844
test_loss: tensor(83.8883)
epoch: 110 train_loss: 77.8613712310791
test_loss: tensor(83.7859)
epoch: 120 train_loss: 77.78895683288575
test_loss: tensor(83.6842)
epoch: 130 train_loss: 77.71744041442871
test_loss: tensor(83.5837)
epoch: 140 train_loss: 77.64949226379395
test_loss: tensor(83.4828)
epoch: 150 train_loss: 77.58303489685059
test_loss: tensor

In [543]:
with torch.no_grad():
    y_pred = model1(Xtest2_tensor)
y = pd.concat([pd.Series(Xtest2[:, 0].reshape(-1), name='send rates'), pd.Series(Xtest2[:, 1].reshape(-1), name='block size'), 
               pd.Series(Ytest2_tensor.numpy().reshape(-1), name='throughput_true'), 
               pd.Series(y_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.to_csv('../../Data/Blockchain Performance Data/Related2/throughput_true_pred_related2.csv')

In [544]:
# Compute the test set MAE RMSE MAPE
import pandas as pd

data = pd.read_csv('../../Data/Blockchain Performance Data/Related2/throughput_true_pred_related2.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

send rates  block size  throughput_true  throughput_pred
0       200.3       190.0            160.4        163.59175
1        70.3        60.0             63.2         65.39337
2       170.5        90.0            127.0        126.72227
3       170.8       200.0            159.6        145.70052
4        90.4       130.0             80.2         80.82825

In [545]:
y = data['throughput_true'].values
y

array([160.4,  63.2, 127. , 159.6,  80.2, 127.6,  97.1, 117.4,  20. ,
       118.3,  81. , 149.7,  83.6, 126.4, 124.6,  99.2, 132.7,  10. ,
        37.6, 119.4,  61.7, 103.2, 134.7,  96.7,   9.9,  48. , 133.6,
       110. , 132.9,  92.5,  50.1,   9.8,  78.3, 121.6,  10. ,  50.2,
        28.5,  53.9, 161.8,  61.5, 109.6, 109.5,  78.4,  37.3, 134.8,
        46.9, 142.9, 123.8, 121.3, 122. ,  38.3,  98.9, 118.8,   9.9,
       121. , 116.2, 117.5,  54.5, 120.1, 131.4,  55.2,  38.3,  97.6,
       104.1, 160.3,  96.9,  54.2, 120.8, 109.5, 118.6,  97. ,  47.5,
       128.5, 125.9,   9.8, 131.8,  30.1, 100.1,  61.4, 119.3])

In [546]:
y_hat = data['throughput_pred'].values
y_hat

array([163.59175 ,  65.39337 , 126.72227 , 145.70052 ,  80.82825 ,
       132.18372 ,  93.5164  , 118.49031 ,  19.893618, 115.607   ,
        81.80599 , 144.77852 ,  87.88615 , 126.313896, 127.31263 ,
        98.7853  , 144.4665  ,  12.293922,  36.98654 , 100.18724 ,
        66.45212 , 105.86481 , 142.73235 ,  97.10418 ,   8.411186,
        45.42862 , 136.79427 ,  95.66663 , 137.80852 ,  93.51097 ,
        48.9878  ,  12.617488,  83.09318 , 118.80838 ,  11.970366,
        49.39942 ,  27.399466,  57.55818 , 162.01744 ,  66.265686,
       108.93072 ,  94.56243 ,  81.06375 ,  39.858364, 141.20622 ,
        47.69355 , 148.29358 , 119.988106, 130.45467 , 123.79704 ,
        38.88768 ,  99.59176 ,  98.13706 ,   8.320244, 127.09264 ,
       115.06426 , 113.55398 ,  55.263054, 117.21995 , 137.68433 ,
        55.94037 ,  38.24056 , 103.68127 , 104.5156  , 143.54242 ,
       100.48498 ,  56.263927, 123.493095, 110.07317 , 126.973885,
       103.621414,  44.45794 , 136.91301 , 132.52228 ,  10.352

In [547]:
from sklearn import metrics

In [549]:
MAE = metrics.mean_absolute_error(y, y_hat)
RMSE = metrics.mean_squared_error(y, y_hat) ** 0.5
MAPE = metrics.mean_absolute_percentage_error(y, y_hat)
print('MAE: ', MAE)
print('RMSE: ', RMSE)
print('MAPE: ', MAPE)

MAE:  4.226891374999998
RMSE:  6.360132407999581
MAPE:  0.05298167150215779


# Choose the optimal block size

## MLP1 to predict latency

In [552]:
TPS = []
for i in range(10,210,10):
    for j in range(20):
        TPS.append(i)
TPS

[10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100

In [553]:
BS = list(range(10, 210, 10)) * 20
BS

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 

In [554]:
len(BS)

400

In [555]:
XpBS = {"Xp": TPS, "BS": BS}
XpBS

{'Xp': [10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  90,
  90,
  90,
  90,
  90,
  90

In [556]:
XpBS = pd.DataFrame(XpBS)
XpBS

Xp   BS
0     10   10
1     10   20
2     10   30
3     10   40
4     10   50
..   ...  ...
395  200  160
396  200  170
397  200  180
398  200  190
399  200  200

[400 rows x 2 columns]

In [557]:
XpBS_values = XpBS.values
XpBS_values

array([[ 10,  10],
       [ 10,  20],
       [ 10,  30],
       [ 10,  40],
       [ 10,  50],
       [ 10,  60],
       [ 10,  70],
       [ 10,  80],
       [ 10,  90],
       [ 10, 100],
       [ 10, 110],
       [ 10, 120],
       [ 10, 130],
       [ 10, 140],
       [ 10, 150],
       [ 10, 160],
       [ 10, 170],
       [ 10, 180],
       [ 10, 190],
       [ 10, 200],
       [ 20,  10],
       [ 20,  20],
       [ 20,  30],
       [ 20,  40],
       [ 20,  50],
       [ 20,  60],
       [ 20,  70],
       [ 20,  80],
       [ 20,  90],
       [ 20, 100],
       [ 20, 110],
       [ 20, 120],
       [ 20, 130],
       [ 20, 140],
       [ 20, 150],
       [ 20, 160],
       [ 20, 170],
       [ 20, 180],
       [ 20, 190],
       [ 20, 200],
       [ 30,  10],
       [ 30,  20],
       [ 30,  30],
       [ 30,  40],
       [ 30,  50],
       [ 30,  60],
       [ 30,  70],
       [ 30,  80],
       [ 30,  90],
       [ 30, 100],
       [ 30, 110],
       [ 30, 120],
       [ 30,

In [558]:
# Normalization
XpBS_minmax = min_max_scaler1.transform(XpBS_values)
XpBS_minmax

array([[0.        , 0.        ],
       [0.        , 0.05263158],
       [0.        , 0.10526316],
       [0.        , 0.15789474],
       [0.        , 0.21052632],
       [0.        , 0.26315789],
       [0.        , 0.31578947],
       [0.        , 0.36842105],
       [0.        , 0.42105263],
       [0.        , 0.47368421],
       [0.        , 0.52631579],
       [0.        , 0.57894737],
       [0.        , 0.63157895],
       [0.        , 0.68421053],
       [0.        , 0.73684211],
       [0.        , 0.78947368],
       [0.        , 0.84210526],
       [0.        , 0.89473684],
       [0.        , 0.94736842],
       [0.        , 1.        ],
       [0.0524109 , 0.        ],
       [0.0524109 , 0.05263158],
       [0.0524109 , 0.10526316],
       [0.0524109 , 0.15789474],
       [0.0524109 , 0.21052632],
       [0.0524109 , 0.26315789],
       [0.0524109 , 0.31578947],
       [0.0524109 , 0.36842105],
       [0.0524109 , 0.42105263],
       [0.0524109 , 0.47368421],
       [0.

In [559]:
XpBS_tensor = torch.from_numpy(XpBS_minmax).type(torch.float32)

In [561]:
with torch.no_grad():
    latency_pred = model(XpBS_tensor)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(latency_pred.numpy().reshape(-1), name='latency_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related2/latency_pred_related2.csv')

In [562]:
y

send rates  block size  latency_pred
0            10          10      0.321697
1            10          20      0.753518
2            10          30      1.072460
3            10          40      1.112280
4            10          50      1.236457
..          ...         ...           ...
395         200         160      1.851533
396         200         170      1.938579
397         200         180      1.893147
398         200         190      1.847714
399         200         200      1.802725

[400 rows x 3 columns]

## MLP2 to predict throughput

In [563]:
# Normalization
XpBS_minmax2 = min_max_scaler2.transform(XpBS_values)
XpBS_minmax2

array([[0.        , 0.        ],
       [0.        , 0.05263158],
       [0.        , 0.10526316],
       [0.        , 0.15789474],
       [0.        , 0.21052632],
       [0.        , 0.26315789],
       [0.        , 0.31578947],
       [0.        , 0.36842105],
       [0.        , 0.42105263],
       [0.        , 0.47368421],
       [0.        , 0.52631579],
       [0.        , 0.57894737],
       [0.        , 0.63157895],
       [0.        , 0.68421053],
       [0.        , 0.73684211],
       [0.        , 0.78947368],
       [0.        , 0.84210526],
       [0.        , 0.89473684],
       [0.        , 0.94736842],
       [0.        , 1.        ],
       [0.0524109 , 0.        ],
       [0.0524109 , 0.05263158],
       [0.0524109 , 0.10526316],
       [0.0524109 , 0.15789474],
       [0.0524109 , 0.21052632],
       [0.0524109 , 0.26315789],
       [0.0524109 , 0.31578947],
       [0.0524109 , 0.36842105],
       [0.0524109 , 0.42105263],
       [0.0524109 , 0.47368421],
       [0.

In [564]:
XpBS_tensor2 = torch.from_numpy(XpBS_minmax2).type(torch.float32)

In [565]:
with torch.no_grad():
    throughput_pred = model1(XpBS_tensor2)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(throughput_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related2/throughput_pred_related2.csv')

In [566]:
y

send rates  block size  throughput_pred
0            10          10        13.980523
1            10          20        13.588173
2            10          30        13.264607
3            10          40        12.941050
4            10          50        12.617488
..          ...         ...              ...
395         200         160       158.270905
396         200         170       159.978088
397         200         180       161.685257
398         200         190       163.392456
399         200         200       165.099625

[400 rows x 3 columns]

In [567]:
with torch.no_grad():
    latency_pred = model(XpBS_tensor)
    throughput_pred = model1(XpBS_tensor2)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(latency_pred.numpy().reshape(-1), name='latency_pred'),
               pd.Series(throughput_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related2/latency_throughput_pred_related2.csv')

## Set the score function to chose the best block

In [568]:
y

send rates  block size  latency_pred  throughput_pred
0            10          10      0.321697        13.980523
1            10          20      0.753518        13.588173
2            10          30      1.072460        13.264607
3            10          40      1.112280        12.941050
4            10          50      1.236457        12.617488
..          ...         ...           ...              ...
395         200         160      1.851533       158.270905
396         200         170      1.938579       159.978088
397         200         180      1.893147       161.685257
398         200         190      1.847714       163.392456
399         200         200      1.802725       165.099625

[400 rows x 4 columns]

In [569]:
for name, group in y.groupby('send rates', sort=False):
    print(name)
    print(group)

10
    send rates  block size  latency_pred  throughput_pred
0           10          10      0.321697        13.980523
1           10          20      0.753518        13.588173
2           10          30      1.072460        13.264607
3           10          40      1.112280        12.941050
4           10          50      1.236457        12.617488
5           10          60      1.373973        12.293922
6           10          70      1.455379        11.970366
7           10          80      1.243009        11.646803
8           10          90      1.165541        11.323236
9           10         100      1.144632        10.999680
10          10         110      1.149619        10.676117
11          10         120      1.169703        10.352552
12          10         130      1.101474        10.028994
13          10         140      1.149733         9.705429
14          10         150      1.173151         9.381872
15          10         160      1.176382         9.058310
16         

In [570]:
la_max_min = y.groupby('send rates', sort=False)['latency_pred'].agg(['max', 'min'])
la_max_min

max       min
send rates                    
10          1.455379  0.321697
20          1.171920  0.162977
30          1.202429  0.127210
40          1.264053  0.114195
50          1.289292  0.101181
60          1.271168  0.088167
70          1.253045  0.074637
80          1.234921  0.042652
90          1.792604  0.018682
100         2.379784  0.006729
110         3.018782  0.017193
120         3.306914  0.106358
130         3.486405  0.195523
140         3.309282  0.243992
150         3.135497  0.294131
160         3.260384  0.453671
170         3.359652  0.676360
180         3.469537  0.997556
190         3.490957  1.376529
200         3.512375  1.763291

In [571]:
la_col=['latency_max', 'latency_min']
la_max_min.columns = la_col
la_max_min

latency_max  latency_min
send rates                          
10             1.455379     0.321697
20             1.171920     0.162977
30             1.202429     0.127210
40             1.264053     0.114195
50             1.289292     0.101181
60             1.271168     0.088167
70             1.253045     0.074637
80             1.234921     0.042652
90             1.792604     0.018682
100            2.379784     0.006729
110            3.018782     0.017193
120            3.306914     0.106358
130            3.486405     0.195523
140            3.309282     0.243992
150            3.135497     0.294131
160            3.260384     0.453671
170            3.359652     0.676360
180            3.469537     0.997556
190            3.490957     1.376529
200            3.512375     1.763291

In [572]:
th_max_min = y.groupby('send rates', sort=False)['throughput_pred'].agg(['max', 'min'])
th_max_min

max         min
send rates                        
10           13.980523    8.320244
20           22.717611   17.217062
30           31.523489   26.346502
40           40.329369   35.381126
50           49.135250   44.281818
60           57.941120   53.411263
70           66.747002   62.442001
80           75.552879   71.346573
90           84.965218   80.476013
100          94.457359   86.623718
110         103.949516   91.898048
120         111.951424   97.522865
130         118.594940  103.147690
140         125.238472  108.422005
150         131.881989  114.046822
160         138.525528  119.671638
170         145.169037  124.945976
180         151.812561  130.570786
190         158.456100  136.195587
200         165.099625  141.469925

In [573]:
th_col=['throughput_max', 'throughput_min']
th_max_min.columns = th_col
th_max_min

throughput_max  throughput_min
send rates                                
10               13.980523        8.320244
20               22.717611       17.217062
30               31.523489       26.346502
40               40.329369       35.381126
50               49.135250       44.281818
60               57.941120       53.411263
70               66.747002       62.442001
80               75.552879       71.346573
90               84.965218       80.476013
100              94.457359       86.623718
110             103.949516       91.898048
120             111.951424       97.522865
130             118.594940      103.147690
140             125.238472      108.422005
150             131.881989      114.046822
160             138.525528      119.671638
170             145.169037      124.945976
180             151.812561      130.570786
190             158.456100      136.195587
200             165.099625      141.469925

In [574]:
# Restore the grouping index to the column
la_max_min.reset_index(inplace=True)
la_max_min

send rates  latency_max  latency_min
0           10     1.455379     0.321697
1           20     1.171920     0.162977
2           30     1.202429     0.127210
3           40     1.264053     0.114195
4           50     1.289292     0.101181
5           60     1.271168     0.088167
6           70     1.253045     0.074637
7           80     1.234921     0.042652
8           90     1.792604     0.018682
9          100     2.379784     0.006729
10         110     3.018782     0.017193
11         120     3.306914     0.106358
12         130     3.486405     0.195523
13         140     3.309282     0.243992
14         150     3.135497     0.294131
15         160     3.260384     0.453671
16         170     3.359652     0.676360
17         180     3.469537     0.997556
18         190     3.490957     1.376529
19         200     3.512375     1.763291

In [575]:
th_max_min.reset_index(inplace=True)
th_max_min

send rates  throughput_max  throughput_min
0           10       13.980523        8.320244
1           20       22.717611       17.217062
2           30       31.523489       26.346502
3           40       40.329369       35.381126
4           50       49.135250       44.281818
5           60       57.941120       53.411263
6           70       66.747002       62.442001
7           80       75.552879       71.346573
8           90       84.965218       80.476013
9          100       94.457359       86.623718
10         110      103.949516       91.898048
11         120      111.951424       97.522865
12         130      118.594940      103.147690
13         140      125.238472      108.422005
14         150      131.881989      114.046822
15         160      138.525528      119.671638
16         170      145.169037      124.945976
17         180      151.812561      130.570786
18         190      158.456100      136.195587
19         200      165.099625      141.469925

In [576]:
la_max = la_max_min['latency_max'].values
la_max = list(la_max)
la_max
len(la_max)

20

In [577]:
la_max_all = []
for i in range(len(la_max)):
    la_max_all.extend([la_max[i]]*20)
    
la_max_all

[1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.4553789,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.1719202,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2024294,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2640531,
 1.2892921,
 1.2892921,
 1.2892921,
 1.2

In [578]:
la_min = la_max_min['latency_min'].values
la_min = list(la_min)
la_min

[0.32169706,
 0.16297717,
 0.12720977,
 0.11419548,
 0.1011814,
 0.0881668,
 0.0746371,
 0.042651623,
 0.018682115,
 0.0067294016,
 0.017193012,
 0.106358424,
 0.19552337,
 0.2439919,
 0.29413092,
 0.4536708,
 0.67635953,
 0.9975556,
 1.3765291,
 1.7632909]

In [579]:
la_min_all = []
for i in range(len(la_min)):
    la_min_all.extend([la_min[i]]*20)
    
la_min_all

[0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.32169706,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.16297717,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.12720977,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,
 0.11419548,

In [580]:
y['latency_min'] = la_min_all
y

send rates  block size  latency_pred  throughput_pred  latency_min
0            10          10      0.321697        13.980523     0.321697
1            10          20      0.753518        13.588173     0.321697
2            10          30      1.072460        13.264607     0.321697
3            10          40      1.112280        12.941050     0.321697
4            10          50      1.236457        12.617488     0.321697
..          ...         ...           ...              ...          ...
395         200         160      1.851533       158.270905     1.763291
396         200         170      1.938579       159.978088     1.763291
397         200         180      1.893147       161.685257     1.763291
398         200         190      1.847714       163.392456     1.763291
399         200         200      1.802725       165.099625     1.763291

[400 rows x 5 columns]

In [581]:
y['latency_max'] = la_max_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.321697        13.980523     0.321697   
1            10          20      0.753518        13.588173     0.321697   
2            10          30      1.072460        13.264607     0.321697   
3            10          40      1.112280        12.941050     0.321697   
4            10          50      1.236457        12.617488     0.321697   
..          ...         ...           ...              ...          ...   
395         200         160      1.851533       158.270905     1.763291   
396         200         170      1.938579       159.978088     1.763291   
397         200         180      1.893147       161.685257     1.763291   
398         200         190      1.847714       163.392456     1.763291   
399         200         200      1.802725       165.099625     1.763291   

     latency_max  
0       1.455379  
1       1.455379  
2       1.455379  
3       1.455379  
4       1.455379  
..           ...  
395     3.512375  
396     3.512375  
397     3.512375  
398     3.512375  
399     3.512375  

[400 rows x 6 columns]

In [582]:
th_max = th_max_min['throughput_max'].values
th_max = list(th_max)
th_max

[13.980523,
 22.717611,
 31.523489,
 40.32937,
 49.13525,
 57.94112,
 66.747,
 75.55288,
 84.96522,
 94.45736,
 103.94952,
 111.95142,
 118.59494,
 125.23847,
 131.88199,
 138.52553,
 145.16904,
 151.81256,
 158.4561,
 165.09962]

In [583]:
th_max_all = []
for i in range(len(th_max)):
    th_max_all.extend([th_max[i]] * 20)
    
th_max_all

[13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 13.980523,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 22.717611,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 31.523489,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 40.32937,
 49.13525,
 49.13525,
 49.13525,
 49.13525,
 49.13525,
 49.1

In [584]:
th_min = th_max_min['throughput_min'].values
th_min = list(th_min)
th_min

[8.320244,
 17.217062,
 26.346502,
 35.381126,
 44.28182,
 53.411263,
 62.442,
 71.34657,
 80.47601,
 86.62372,
 91.89805,
 97.522865,
 103.14769,
 108.422005,
 114.04682,
 119.67164,
 124.94598,
 130.57079,
 136.19559,
 141.46992]

In [585]:
th_min_all = []
for i in range(len(th_min)):
    th_min_all.extend([th_min[i]] * 20)
    
th_min_all

[8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 8.320244,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 17.217062,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 26.346502,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 35.381126,
 44.28182,
 44.28182,
 44.28182,
 44.28182,
 44.28182,
 44.2

In [586]:
y['throughput_min'] = th_min_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.321697        13.980523     0.321697   
1            10          20      0.753518        13.588173     0.321697   
2            10          30      1.072460        13.264607     0.321697   
3            10          40      1.112280        12.941050     0.321697   
4            10          50      1.236457        12.617488     0.321697   
..          ...         ...           ...              ...          ...   
395         200         160      1.851533       158.270905     1.763291   
396         200         170      1.938579       159.978088     1.763291   
397         200         180      1.893147       161.685257     1.763291   
398         200         190      1.847714       163.392456     1.763291   
399         200         200      1.802725       165.099625     1.763291   

     latency_max  throughput_min  
0       1.455379        8.320244  
1       1.455379        8.320244  
2       1.455379        8.320244  
3       1.455379        8.320244  
4       1.455379        8.320244  
..           ...             ...  
395     3.512375      141.469925  
396     3.512375      141.469925  
397     3.512375      141.469925  
398     3.512375      141.469925  
399     3.512375      141.469925  

[400 rows x 7 columns]

In [587]:
y['throughput_max'] = th_max_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.321697        13.980523     0.321697   
1            10          20      0.753518        13.588173     0.321697   
2            10          30      1.072460        13.264607     0.321697   
3            10          40      1.112280        12.941050     0.321697   
4            10          50      1.236457        12.617488     0.321697   
..          ...         ...           ...              ...          ...   
395         200         160      1.851533       158.270905     1.763291   
396         200         170      1.938579       159.978088     1.763291   
397         200         180      1.893147       161.685257     1.763291   
398         200         190      1.847714       163.392456     1.763291   
399         200         200      1.802725       165.099625     1.763291   

     latency_max  throughput_min  throughput_max  
0       1.455379        8.320244       13.980523  
1       1.455379        8.320244       13.980523  
2       1.455379        8.320244       13.980523  
3       1.455379        8.320244       13.980523  
4       1.455379        8.320244       13.980523  
..           ...             ...             ...  
395     3.512375      141.469925      165.099625  
396     3.512375      141.469925      165.099625  
397     3.512375      141.469925      165.099625  
398     3.512375      141.469925      165.099625  
399     3.512375      141.469925      165.099625  

[400 rows x 8 columns]

In [588]:
y.to_csv('../../Data/Result/Related2/latency_throughput_pred_max_min_related2.csv')

### choose different weights

In [589]:
# Read the processed data directly
y = pd.read_csv('../../Data/Result/Related2/latency_throughput_pred_max_min_related2.csv')
y

Unnamed: 0  send rates  block size  latency_pred  throughput_pred  \
0             0          10          10      0.321697        13.980523   
1             1          10          20      0.753518        13.588173   
2             2          10          30      1.072460        13.264607   
3             3          10          40      1.112280        12.941050   
4             4          10          50      1.236457        12.617488   
..          ...         ...         ...           ...              ...   
395         395         200         160      1.851533       158.270900   
396         396         200         170      1.938579       159.978090   
397         397         200         180      1.893147       161.685260   
398         398         200         190      1.847714       163.392460   
399         399         200         200      1.802725       165.099620   

     latency_min  latency_max  throughput_min  throughput_max  
0       0.321697     1.455379        8.320244       13.980523  
1       0.321697     1.455379        8.320244       13.980523  
2       0.321697     1.455379        8.320244       13.980523  
3       0.321697     1.455379        8.320244       13.980523  
4       0.321697     1.455379        8.320244       13.980523  
..           ...          ...             ...             ...  
395     1.763291     3.512375      141.469920      165.099620  
396     1.763291     3.512375      141.469920      165.099620  
397     1.763291     3.512375      141.469920      165.099620  
398     1.763291     3.512375      141.469920      165.099620  
399     1.763291     3.512375      141.469920      165.099620  

[400 rows x 9 columns]

In [599]:
alpha = 0.9
beta = 0.1

In [600]:
latency_score = alpha * ((y['latency_max'] - y['latency_pred']) / (y['latency_max'] - y['latency_min']))

In [601]:
throughput_score = beta * ((y['throughput_pred'] - y['throughput_min']) / (y['throughput_max'] - y['throughput_min']))

In [602]:
y_score = latency_score.values + throughput_score.values
y_score

array([1.00000000e+00, 6.50256992e-01, 3.91340950e-01, 3.54012712e-01,
       2.49715756e-01, 1.34828933e-01, 6.44866092e-02, 2.27364992e-01,
       2.83148654e-01, 2.94031580e-01, 2.84356154e-01, 2.62694869e-01,
       3.11144331e-01, 2.67116136e-01, 2.42809171e-01, 2.34527963e-01,
       2.23086803e-01, 2.15883137e-01, 2.16870846e-01, 2.31969935e-01,
       1.00000000e+00, 7.79955243e-01, 4.32010112e-01, 3.15359348e-01,
       1.98708922e-01, 7.83197436e-02, 1.30982936e-01, 1.16935965e-01,
       6.55326227e-02, 6.65492366e-02, 5.62180229e-02, 4.50123231e-02,
       4.72242161e-02, 3.54033592e-02, 1.76471476e-02, 1.56882053e-02,
       1.24543184e-02, 1.39512337e-04, 1.25883961e-02, 2.83712381e-02,
       1.00000000e+00, 8.84928903e-01, 6.53446701e-01, 5.27792493e-01,
       4.02138286e-01, 2.62012943e-01, 2.19202449e-01, 1.72676260e-01,
       9.95960285e-02, 8.17853841e-02, 7.25986936e-02, 6.21738367e-02,
       2.50000821e-02, 4.84663454e-02, 3.95698432e-02, 3.64991662e-02,
      

In [603]:
y['score'] = y_score

In [604]:
y.to_csv('../../Data/Result/Related2//latency_throughput_score_alpha' + str(alpha) + '_beta' + str(beta) + '_related1.csv')

In [605]:
y

Unnamed: 0  send rates  block size  latency_pred  throughput_pred  \
0             0          10          10      0.321697        13.980523   
1             1          10          20      0.753518        13.588173   
2             2          10          30      1.072460        13.264607   
3             3          10          40      1.112280        12.941050   
4             4          10          50      1.236457        12.617488   
..          ...         ...         ...           ...              ...   
395         395         200         160      1.851533       158.270900   
396         396         200         170      1.938579       159.978090   
397         397         200         180      1.893147       161.685260   
398         398         200         190      1.847714       163.392460   
399         399         200         200      1.802725       165.099620   

     latency_min  latency_max  throughput_min  throughput_max     score  
0       0.321697     1.455379        8.320244       13.980523  1.000000  
1       0.321697     1.455379        8.320244       13.980523  0.650257  
2       0.321697     1.455379        8.320244       13.980523  0.391341  
3       0.321697     1.455379        8.320244       13.980523  0.354013  
4       0.321697     1.455379        8.320244       13.980523  0.249716  
..           ...          ...             ...             ...       ...  
395     1.763291     3.512375      141.469920      165.099620  0.925696  
396     1.763291     3.512375      141.469920      165.099620  0.888130  
397     1.763291     3.512375      141.469920      165.099620  0.918733  
398     1.763291     3.512375      141.469920      165.099620  0.949335  
399     1.763291     3.512375      141.469920      165.099620  0.979709  

[400 rows x 10 columns]

In [597]:
# for name, group in y_filter.groupby('send rates', sort=False):
#     print(name)
#     print(group)

In [598]:
score_max = y_filter.groupby('send rates', sort=False)['score'].agg(['max'])
score_max

NameError: name 'y_filter' is not defined

In [186]:
score_col=['score_max']
score_max.columns = score_col
score_max

score_max
send rates           
110          0.900000
120          0.957629
130          0.935767
140          0.975530
150          0.959464
160          0.948897
170          0.942622
180          0.937040
190          0.932751
200          0.931587

In [173]:
score_max.reset_index(inplace=True)
score_max

send rates  score_max
0         110   0.900000
1         120   0.957629
2         130   0.935767
3         140   0.975530
4         150   0.959464
5         160   0.948897
6         170   0.942622
7         180   0.937040
8         190   0.932751
9         200   0.931587

In [174]:
score_max = score_max['score_max'].values
score_max = list(score_max)
score_max

[0.9,
 0.9576292009793012,
 0.935766542296804,
 0.9755297281665295,
 0.9594641954417422,
 0.948897047652697,
 0.9426218442660812,
 0.9370401678061414,
 0.9327513508027239,
 0.9315867846142339]

In [175]:
score_max_all = []
for i in range(len(score_max)):
    score_max_all.extend([score_max[i]] * 20)
    
score_max_all

[0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.9576292009793012,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.935766542296804,
 0.9755297281665295,
 0.9755297281665295,
 0.975529728166529

In [177]:
y_filter['score_max'] = score_max_all
y_filter

C:\Users\cswan\AppData\Local\Temp\ipykernel_1808\1654378504.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_filter['score_max'] = score_max_all


Unnamed: 0  send rates  block size  latency_pred  throughput_pred  \
200         200         110          10      0.116099        92.969315   
201         201         110          20      0.451027        94.346720   
202         202         110          30      0.262916        94.403610   
203         203         110          40      0.513995        94.460520   
204         204         110          50      0.426948        94.517420   
..          ...         ...         ...           ...              ...   
395         395         200         160      1.715595       159.231080   
396         396         200         170      1.646274       161.011200   
397         397         200         180      1.592673       162.791320   
398         398         200         190      1.570900       164.571460   
399         399         200         200      1.548800       166.351600   

     latency_min  latency_max  throughput_min  throughput_max     score  \
200     0.116099     0.824487       92.969315       95.370895  0.900000   
201     0.116099     0.824487       92.969315       95.370895  0.531831   
202     0.116099     0.824487       92.969315       95.370895  0.773194   
203     0.116099     0.824487       92.969315       95.370895  0.456569   
204     0.116099     0.824487       92.969315       95.370895  0.569531   
..           ...          ...             ...             ...       ...   
395     0.863849     2.489892      132.525270      166.351600  0.507516   
396     0.863849     2.489892      132.525270      166.351600  0.551147   
397     0.863849     2.489892      132.525270      166.351600  0.586077   
398     0.863849     2.489892      132.525270      166.351600  0.603391   
399     0.863849     2.489892      132.525270      166.351600  0.620886   

     score_max  
200   0.900000  
201   0.900000  
202   0.900000  
203   0.900000  
204   0.900000  
..         ...  
395   0.931587  
396   0.931587  
397   0.931587  
398   0.931587  
399   0.931587  

[200 rows x 11 columns]

In [178]:
result = y_filter[y_filter['score'] == y_filter['score_max']]
result

Unnamed: 0  send rates  block size  latency_pred  throughput_pred  \
200         200         110          10      0.116099        92.969315   
222         222         120          30      0.307015       100.925110   
242         242         130          30      0.326867       105.320656   
266         266         140          70      0.410121       116.836700   
286         286         150          70      0.427485       121.232240   
306         306         160          70      0.444849       125.627770   
326         326         170          70      0.506402       130.023300   
346         346         180          70      0.661163       134.418850   
366         366         190          70      0.806855       138.814380   
386         386         200          70      0.863849       143.209920   

     latency_min  latency_max  throughput_min  throughput_max     score  \
200     0.116099     0.824487       92.969315       95.370895  0.900000   
222     0.307015     0.866201       97.364850      103.542725  0.957629   
242     0.326867     0.896848      101.760390      111.714570  0.935767   
266     0.408295     1.135574      106.155940      119.886380  0.975530   
286     0.425659     1.488943      110.551470      128.058230  0.959464   
306     0.443023     1.719399      114.947014      136.230060  0.948897   
326     0.506402     1.949942      119.342545      144.401890  0.942622   
346     0.661163     2.181794      123.738075      152.573730  0.937040   
366     0.806855     2.339685      128.133480      160.745570  0.932751   
386     0.863849     2.489892      132.525270      166.351600  0.931587   

     score_max  
200   0.900000  
222   0.957629  
242   0.935767  
266   0.975530  
286   0.959464  
306   0.948897  
326   0.942622  
346   0.937040  
366   0.932751  
386   0.931587

In [179]:
result.to_csv('./best_block_size_alpha' + str(alpha) + '_beta' + str(beta) + '_related1.csv')