# Import library and split data

In [119]:
import pandas as pd

In [120]:
df = pd.read_csv('../../Data/Blockchain Performance Data/Related3/BPD_related3.csv')
df

Send Rates  Block Size  Avg Latency  Throughput
0          10.0          10         0.30        10.0
1          10.0          20         0.81        10.0
2          10.0          30         1.13         9.9
3          10.0          40         1.14         9.9
4          10.0          50         1.14         9.9
..          ...         ...          ...         ...
395       193.2         160         2.90       159.0
396       200.9         170         2.23       154.9
397       199.8         180         2.01       157.2
398       200.6         190         2.11       160.4
399       195.5         200         2.31       161.8

[400 rows x 4 columns]

In [121]:
xy = df.values
xy

array([[ 10.  ,  10.  ,   0.3 ,  10.  ],
       [ 10.  ,  20.  ,   0.81,  10.  ],
       [ 10.  ,  30.  ,   1.13,   9.9 ],
       ...,
       [199.8 , 180.  ,   2.01, 157.2 ],
       [200.6 , 190.  ,   2.11, 160.4 ],
       [195.5 , 200.  ,   2.31, 161.8 ]])

In [122]:
import torch
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [123]:
# set random seed
seed = 42
torch.manual_seed(seed)

In [124]:
# Read raw data and divide training set and test set
raw_data = xy
X = raw_data[:, :2]
Y1 = raw_data[:, -2:-1]
Y2 = raw_data[:, -1:]

In [125]:
X

array([[ 10. ,  10. ],
       [ 10. ,  20. ],
       [ 10. ,  30. ],
       [ 10. ,  40. ],
       [ 10. ,  50. ],
       [ 10. ,  60. ],
       [ 10. ,  70. ],
       [ 10. ,  80. ],
       [ 10. ,  90. ],
       [ 10. , 100. ],
       [ 10. , 110. ],
       [ 10. , 120. ],
       [ 10. , 130. ],
       [ 10. , 140. ],
       [ 10. , 150. ],
       [ 10. , 160. ],
       [ 10. , 170. ],
       [ 10. , 180. ],
       [ 10. , 190. ],
       [ 10. , 200. ],
       [ 20.1,  10. ],
       [ 20.1,  20. ],
       [ 20.1,  30. ],
       [ 20.1,  40. ],
       [ 20.1,  50. ],
       [ 20.1,  60. ],
       [ 20.1,  70. ],
       [ 20.1,  80. ],
       [ 20.1,  90. ],
       [ 20.1, 100. ],
       [ 20.1, 110. ],
       [ 20.1, 120. ],
       [ 20.1, 130. ],
       [ 20.1, 140. ],
       [ 20.1, 150. ],
       [ 20.1, 160. ],
       [ 20.1, 170. ],
       [ 20.1, 180. ],
       [ 20.1, 190. ],
       [ 20.1, 200. ],
       [ 30.1,  10. ],
       [ 30.1,  20. ],
       [ 30.1,  30. ],
       [ 30

In [126]:
Y1

array([[0.3 ],
       [0.81],
       [1.13],
       [1.14],
       [1.14],
       [1.12],
       [1.16],
       [1.18],
       [1.18],
       [1.18],
       [1.13],
       [1.14],
       [1.21],
       [1.19],
       [1.14],
       [1.16],
       [1.17],
       [1.18],
       [1.18],
       [1.17],
       [0.18],
       [0.44],
       [0.71],
       [0.96],
       [1.13],
       [1.14],
       [1.14],
       [1.17],
       [1.2 ],
       [1.17],
       [1.17],
       [1.15],
       [1.17],
       [1.18],
       [1.16],
       [1.17],
       [1.18],
       [1.16],
       [1.14],
       [1.18],
       [0.13],
       [0.31],
       [0.5 ],
       [0.66],
       [0.83],
       [1.04],
       [1.16],
       [1.14],
       [1.16],
       [1.15],
       [1.15],
       [1.15],
       [1.17],
       [1.16],
       [1.16],
       [1.16],
       [1.17],
       [1.15],
       [1.14],
       [1.17],
       [0.1 ],
       [0.24],
       [0.39],
       [0.51],
       [0.64],
       [0.81],
       [0.

In [127]:
Y2

array([[ 10. ],
       [ 10. ],
       [  9.9],
       [  9.9],
       [  9.9],
       [ 10. ],
       [  9.8],
       [ 10. ],
       [ 10. ],
       [  9.8],
       [ 10. ],
       [  9.9],
       [  9.8],
       [  9.9],
       [  9.9],
       [  9.8],
       [  9.8],
       [  9.9],
       [  9.9],
       [ 10. ],
       [ 20.1],
       [ 20.1],
       [ 19.4],
       [ 20.1],
       [ 19.4],
       [ 20. ],
       [ 19.3],
       [ 19.9],
       [ 19.9],
       [ 20. ],
       [ 19.3],
       [ 19.4],
       [ 19.3],
       [ 19.8],
       [ 19.9],
       [ 19.9],
       [ 19.8],
       [ 19.9],
       [ 19.3],
       [ 20. ],
       [ 30.1],
       [ 30.1],
       [ 28.5],
       [ 30.1],
       [ 30.1],
       [ 29.3],
       [ 28.7],
       [ 28.6],
       [ 28.5],
       [ 28.5],
       [ 28.5],
       [ 28.5],
       [ 28.8],
       [ 28.5],
       [ 28.6],
       [ 28.4],
       [ 28.5],
       [ 28.6],
       [ 28.8],
       [ 28.7],
       [ 40.1],
       [ 40.1],
       [

# MLP1(send rates, block size) = latency

In [134]:
# Split training set and test set
Xtrain1, Xtest1, Ytrain1, Ytest1 = train_test_split(X, Y1, test_size=0.2, random_state=1)

In [135]:
# test set
Xtest1

array([[200.6, 190. ],
       [ 70.3,  60. ],
       [170.6,  90. ],
       [170.7, 200. ],
       [ 90.3, 130. ],
       [180.6,  30. ],
       [100.4, 180. ],
       [150.3, 120. ],
       [ 20.1, 100. ],
       [150.7,  50. ],
       [ 90.2, 150. ],
       [187.7, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [169.5,  20. ],
       [120.4,  80. ],
       [190.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.6,  30. ],
       [200.6,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.5,  70. ],
       [110.4,  20. ],
       [189.9,  20. ],
       [110.2,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.4, 160. ],
       [ 10. ,  70. ],
       [ 50.2,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [199.8, 180. ],
       [ 70.3, 200. ],
       [140.5,  90. ],
       [110.4,  50. ],
       [ 90.4, 120. ],
       [ 40

In [70]:
Ytest1

array([[2.11],
       [0.55],
       [0.97],
       [1.22],
       [0.88],
       [0.9 ],
       [0.79],
       [0.8 ],
       [1.17],
       [0.41],
       [0.9 ],
       [1.2 ],
       [0.68],
       [0.48],
       [0.39],
       [0.67],
       [1.22],
       [1.12],
       [1.15],
       [0.34],
       [0.25],
       [0.22],
       [1.34],
       [0.89],
       [1.18],
       [1.24],
       [1.33],
       [0.13],
       [1.44],
       [0.66],
       [0.2 ],
       [1.14],
       [0.48],
       [0.88],
       [1.16],
       [0.09],
       [1.14],
       [0.28],
       [2.01],
       [1.02],
       [0.59],
       [0.31],
       [1.01],
       [0.39],
       [1.55],
       [0.68],
       [2.7 ],
       [1.61],
       [2.89],
       [0.82],
       [0.81],
       [0.44],
       [0.72],
       [1.18],
       [0.95],
       [0.46],
       [0.74],
       [1.23],
       [0.81],
       [1.59],
       [0.8 ],
       [1.08],
       [0.94],
       [0.49],
       [1.42],
       [0.2 ],
       [0.

In [71]:
# property scaling
min_max_scaler1 = preprocessing.MinMaxScaler()

In [72]:
# Scaling training set data
Xtrain1_minmax = min_max_scaler1.fit_transform(Xtrain1)
Xtrain1_minmax

array([[0.21058146, 0.68421053],
       [0.05290728, 0.15789474],
       [0.73598743, 1.        ],
       [0.        , 0.68421053],
       [0.21058146, 0.52631579],
       [0.15819801, 0.05263158],
       [0.99738083, 0.05263158],
       [0.52592981, 0.68421053],
       [0.99685699, 0.57894737],
       [0.31587218, 0.36842105],
       [0.36877947, 1.        ],
       [0.89313777, 0.78947368],
       [0.73598743, 0.15789474],
       [0.83970665, 0.94736842],
       [0.42116291, 0.05263158],
       [0.78837087, 0.        ],
       [0.68412782, 0.89473684],
       [0.73493976, 0.47368421],
       [0.68360398, 0.        ],
       [0.42063908, 0.68421053],
       [0.21058146, 0.10526316],
       [0.94342588, 0.36842105],
       [0.42063908, 1.        ],
       [0.05290728, 0.36842105],
       [0.21058146, 0.47368421],
       [0.78837087, 0.57894737],
       [0.15819801, 0.68421053],
       [0.57726558, 0.68421053],
       [0.73546359, 0.94736842],
       [0.6291252 , 0.52631579],
       [0.

In [73]:
# Apply the same scaling to the test set data
Xtest1_minmax = min_max_scaler1.transform(Xtest1)
Xtest1_minmax

array([[0.9984285 , 0.94736842],
       [0.31587218, 0.26315789],
       [0.84127816, 0.42105263],
       [0.84180199, 1.        ],
       [0.42063908, 0.63157895],
       [0.8936616 , 0.10526316],
       [0.47354636, 0.89473684],
       [0.73493976, 0.57894737],
       [0.05290728, 0.47368421],
       [0.7370351 , 0.21052632],
       [0.42011524, 0.73684211],
       [0.93085385, 0.63157895],
       [0.47354636, 0.42105263],
       [0.84127816, 0.21052632],
       [0.83551598, 0.05263158],
       [0.57831325, 0.36842105],
       [0.94552122, 0.57894737],
       [0.        , 0.26315789],
       [0.15819801, 0.94736842],
       [0.57831325, 0.15789474],
       [0.31639602, 0.10526316],
       [0.63174437, 0.10526316],
       [0.9984285 , 0.10526316],
       [0.52645364, 0.73684211],
       [0.        , 0.89473684],
       [0.21058146, 0.63157895],
       [0.94552122, 0.31578947],
       [0.52592981, 0.05263158],
       [0.94237821, 0.05263158],
       [0.52488214, 0.36842105],
       [0.

In [74]:
Xtest1_tensor = torch.from_numpy(Xtest1_minmax).type(torch.float32)
Ytest1_tensor = torch.from_numpy(Ytest1).type(torch.float32)

In [75]:
Xtest1_tensor

tensor([[0.9984, 0.9474],
        [0.3159, 0.2632],
        [0.8413, 0.4211],
        [0.8418, 1.0000],
        [0.4206, 0.6316],
        [0.8937, 0.1053],
        [0.4735, 0.8947],
        [0.7349, 0.5789],
        [0.0529, 0.4737],
        [0.7370, 0.2105],
        [0.4201, 0.7368],
        [0.9309, 0.6316],
        [0.4735, 0.4211],
        [0.8413, 0.2105],
        [0.8355, 0.0526],
        [0.5783, 0.3684],
        [0.9455, 0.5789],
        [0.0000, 0.2632],
        [0.1582, 0.9474],
        [0.5783, 0.1579],
        [0.3164, 0.1053],
        [0.6317, 0.1053],
        [0.9984, 0.1053],
        [0.5265, 0.7368],
        [0.0000, 0.8947],
        [0.2106, 0.6316],
        [0.9455, 0.3158],
        [0.5259, 0.0526],
        [0.9424, 0.0526],
        [0.5249, 0.3684],
        [0.2106, 0.0526],
        [0.0000, 0.2105],
        [0.4212, 0.2632],
        [0.6831, 0.7895],
        [0.0000, 0.3158],
        [0.2106, 0.0000],
        [0.1053, 0.9474],
        [0.2635, 0.1053],
        [0.9

In [76]:
# batch the training dataset
# prepare dataset
class BlockChainDataset(Dataset):
    def __init__(self, data, label):
        self.len = data.shape[0]
        self.x_data = torch.from_numpy(data).type(torch.float32)
        self.y_data = torch.from_numpy(label).type(torch.float32)
        
        
    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]
    
    def __len__(self):
        return self.len

In [77]:
train_dataset = BlockChainDataset(Xtrain1_minmax, Ytrain1)
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=False)

In [78]:
import torch.nn as nn
import torch.optim as optim

In [79]:
# design model using class
class Lat(torch.nn.Module):
    def __init__(self):
        super(Lat, self).__init__()
        self.fc1 = nn.Linear(2, 64)
        self.fc2 = nn.Linear(64, 8)
        self.relu = nn.ReLU()
        self.fc3 = nn.Linear(8, 1)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out
    
    
model = Lat()

In [80]:
# net = nn.Sequential(
#     nn.Linear(2, 64), nn.BatchNorm1d(64), nn.Dropout(p=0.5), nn.ReLU(),
#     nn.Linear(64, 64), nn.BatchNorm1d(64), nn.Dropout(p=0.5), nn.ReLU(),
#     nn.Linear(64, 1))


# model = net

In [81]:
# construct loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [82]:
# traning cycle forward, backward, update
def train(epoch):
    train_loss = 0.0
    for batch_idx, (inputs, labels) in enumerate(train_loader, 0):
        y_pred = model(inputs)
        loss = criterion(y_pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * labels.shape[0]
    if (epoch + 1) % 10 == 0:
        print('epoch:', epoch + 1, 'train_loss:', train_loss / len(Xtrain1))
        

def test():
    with torch.no_grad():
        y_pred = model(Xtest1_tensor)
        loss = criterion(y_pred, Ytest1_tensor)
        print('test_loss:', loss)

In [282]:
if __name__ == '__main__':
    for epoch in range(5000):
        train(epoch)
        if (epoch + 1) % 10 == 0:
            model.eval()
            test()

epoch: 10 train_loss: 0.010410415939986706
test_loss: tensor(0.0628)
epoch: 20 train_loss: 0.011669123591855169
test_loss: tensor(0.0604)
epoch: 30 train_loss: 0.015119113959372044
test_loss: tensor(0.0691)
epoch: 40 train_loss: 0.011270327679812907
test_loss: tensor(0.0685)
epoch: 50 train_loss: 0.01103515112772584
test_loss: tensor(0.0717)
epoch: 60 train_loss: 0.008162179286591709
test_loss: tensor(0.0713)
epoch: 70 train_loss: 0.009942533797584474
test_loss: tensor(0.0734)
epoch: 80 train_loss: 0.009139689500443637
test_loss: tensor(0.0722)
epoch: 90 train_loss: 0.008866382297128439
test_loss: tensor(0.0691)
epoch: 100 train_loss: 0.008879442233592272
test_loss: tensor(0.0700)
epoch: 110 train_loss: 0.009302773722447455
test_loss: tensor(0.0691)
epoch: 120 train_loss: 0.010284598218277097
test_loss: tensor(0.0661)
epoch: 130 train_loss: 0.010853838548064232
test_loss: tensor(0.0670)
epoch: 140 train_loss: 0.010591573407873511
test_loss: tensor(0.0630)
epoch: 150 train_loss: 0.01246

epoch: 1210 train_loss: 0.00902127088047564
test_loss: tensor(0.0676)
epoch: 1220 train_loss: 0.011413412494584918
test_loss: tensor(0.0644)
epoch: 1230 train_loss: 0.008963711792603135
test_loss: tensor(0.0732)
epoch: 1240 train_loss: 0.010761992167681455
test_loss: tensor(0.0736)
epoch: 1250 train_loss: 0.010085003031417728
test_loss: tensor(0.0695)
epoch: 1260 train_loss: 0.015766722802072763
test_loss: tensor(0.0657)
epoch: 1270 train_loss: 0.010102657694369554
test_loss: tensor(0.0741)
epoch: 1280 train_loss: 0.011593162966892123
test_loss: tensor(0.0785)
epoch: 1290 train_loss: 0.010319568123668433
test_loss: tensor(0.0728)
epoch: 1300 train_loss: 0.014261350594460964
test_loss: tensor(0.0699)
epoch: 1310 train_loss: 0.010295926709659398
test_loss: tensor(0.0680)
epoch: 1320 train_loss: 0.00853138065431267
test_loss: tensor(0.0624)
epoch: 1330 train_loss: 0.009388642082922161
test_loss: tensor(0.0659)
epoch: 1340 train_loss: 0.010804539127275348
test_loss: tensor(0.0626)
epoch: 1

epoch: 2410 train_loss: 0.009333614353090524
test_loss: tensor(0.0754)
epoch: 2420 train_loss: 0.009414323884993792
test_loss: tensor(0.0735)
epoch: 2430 train_loss: 0.010064744716510176
test_loss: tensor(0.0697)
epoch: 2440 train_loss: 0.008271208102814852
test_loss: tensor(0.0644)
epoch: 2450 train_loss: 0.009251508093439043
test_loss: tensor(0.0646)
epoch: 2460 train_loss: 0.010524035105481744
test_loss: tensor(0.0670)
epoch: 2470 train_loss: 0.010686353291384875
test_loss: tensor(0.0737)
epoch: 2480 train_loss: 0.009937603888101876
test_loss: tensor(0.0728)
epoch: 2490 train_loss: 0.011664833407849073
test_loss: tensor(0.0679)
epoch: 2500 train_loss: 0.00876742082182318
test_loss: tensor(0.0631)
epoch: 2510 train_loss: 0.009821443073451518
test_loss: tensor(0.0614)
epoch: 2520 train_loss: 0.010613842005841433
test_loss: tensor(0.0655)
epoch: 2530 train_loss: 0.010294836317189037
test_loss: tensor(0.0627)
epoch: 2540 train_loss: 0.010605359287001192
test_loss: tensor(0.0595)
epoch: 

epoch: 3590 train_loss: 0.00879057738929987
test_loss: tensor(0.0640)
epoch: 3600 train_loss: 0.009414127166382968
test_loss: tensor(0.0627)
epoch: 3610 train_loss: 0.008135971985757351
test_loss: tensor(0.0663)
epoch: 3620 train_loss: 0.007659137435257435
test_loss: tensor(0.0666)
epoch: 3630 train_loss: 0.0080071218078956
test_loss: tensor(0.0613)
epoch: 3640 train_loss: 0.007626781426370144
test_loss: tensor(0.0634)
epoch: 3650 train_loss: 0.008690246962942183
test_loss: tensor(0.0604)
epoch: 3660 train_loss: 0.008711417834274472
test_loss: tensor(0.0786)
epoch: 3670 train_loss: 0.010166504490189254
test_loss: tensor(0.0708)
epoch: 3680 train_loss: 0.016156853036955
test_loss: tensor(0.0602)
epoch: 3690 train_loss: 0.0097215938847512
test_loss: tensor(0.0800)
epoch: 3700 train_loss: 0.012472121557220817
test_loss: tensor(0.0753)
epoch: 3710 train_loss: 0.010687964130192995
test_loss: tensor(0.0629)
epoch: 3720 train_loss: 0.009525097697041929
test_loss: tensor(0.0648)
epoch: 3730 tr

epoch: 4790 train_loss: 0.009696819889359175
test_loss: tensor(0.0628)
epoch: 4800 train_loss: 0.010321252117864787
test_loss: tensor(0.0659)
epoch: 4810 train_loss: 0.01249980553984642
test_loss: tensor(0.0683)
epoch: 4820 train_loss: 0.007993344590067864
test_loss: tensor(0.0685)
epoch: 4830 train_loss: 0.008328157174400986
test_loss: tensor(0.0689)
epoch: 4840 train_loss: 0.008906727703288198
test_loss: tensor(0.0637)
epoch: 4850 train_loss: 0.00870637665502727
test_loss: tensor(0.0635)
epoch: 4860 train_loss: 0.011591250146739184
test_loss: tensor(0.0587)
epoch: 4870 train_loss: 0.010406506014987826
test_loss: tensor(0.0768)
epoch: 4880 train_loss: 0.01103874370455742
test_loss: tensor(0.0774)
epoch: 4890 train_loss: 0.010328073054552078
test_loss: tensor(0.0745)
epoch: 4900 train_loss: 0.009946882678195833
test_loss: tensor(0.0759)
epoch: 4910 train_loss: 0.007961149676702917
test_loss: tensor(0.0655)
epoch: 4920 train_loss: 0.00815528524108231
test_loss: tensor(0.0679)
epoch: 493

In [283]:
Xtest1

array([[200.6, 190. ],
       [ 70.3,  60. ],
       [170.6,  90. ],
       [170.7, 200. ],
       [ 90.3, 130. ],
       [180.6,  30. ],
       [100.4, 180. ],
       [150.3, 120. ],
       [ 20.1, 100. ],
       [150.7,  50. ],
       [ 90.2, 150. ],
       [187.7, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [169.5,  20. ],
       [120.4,  80. ],
       [190.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.6,  30. ],
       [200.6,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.5,  70. ],
       [110.4,  20. ],
       [189.9,  20. ],
       [110.2,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.4, 160. ],
       [ 10. ,  70. ],
       [ 50.2,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [199.8, 180. ],
       [ 70.3, 200. ],
       [140.5,  90. ],
       [110.4,  50. ],
       [ 90.4, 120. ],
       [ 40

In [284]:
Xtest1[:, 1].reshape(-1)

array([190.,  60.,  90., 200., 130.,  30., 180., 120., 100.,  50., 150.,
       130.,  90.,  50.,  20.,  80., 120.,  60., 190.,  40.,  30.,  30.,
        30., 150., 180., 130.,  70.,  20.,  20.,  80.,  20.,  50.,  60.,
       160.,  70.,  10., 190.,  30., 180., 200.,  90.,  50., 120.,  30.,
        60.,  60., 100.,  80., 150., 190.,  60.,  60., 100., 190., 170.,
        70., 130., 180., 190.,  10.,  80.,  80., 150.,  70., 150.,  30.,
        70., 110., 110., 130., 190., 160., 110.,  80., 120.,  80.,  20.,
        10., 130.,  50.])

In [285]:
with torch.no_grad():
    y_pred = model(Xtest1_tensor)
y = pd.concat([pd.Series(Xtest1[:, 0].reshape(-1), name='send rates'), pd.Series(Xtest1[:, 1].reshape(-1), name='block size'), 
               pd.Series(Ytest1_tensor.numpy().reshape(-1), name='latency_true'), pd.Series(y_pred.numpy().reshape(-1), name='latency_pred')], 
              axis=1)
y.to_csv('../../Data/Result/Related3/latency_true_pred_related3.csv')

In [286]:
# Compute test set MAE RMSE MAPE
import pandas as pd

data = pd.read_csv('../../Data/Result/Related3/latency_true_pred_related3.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

send rates  block size  latency_true  latency_pred
0       200.6       190.0          2.11      2.488863
1        70.3        60.0          0.55      0.488265
2       170.6        90.0          0.97      0.930942
3       170.7       200.0          1.22      1.061628
4        90.3       130.0          0.88      0.819647

In [287]:
y = data['latency_true'].values
y

array([2.11, 0.55, 0.97, 1.22, 0.88, 0.9 , 0.79, 0.8 , 1.17, 0.41, 0.9 ,
       1.2 , 0.68, 0.48, 0.39, 0.67, 1.22, 1.12, 1.15, 0.34, 0.25, 0.22,
       1.34, 0.89, 1.18, 1.24, 1.33, 0.13, 1.44, 0.66, 0.2 , 1.14, 0.48,
       0.88, 1.16, 0.09, 1.14, 0.28, 2.01, 1.02, 0.59, 0.31, 1.01, 0.39,
       1.55, 0.68, 2.7 , 1.61, 2.89, 0.82, 0.81, 0.44, 0.72, 1.18, 0.95,
       0.46, 0.74, 1.23, 0.81, 1.59, 0.8 , 1.08, 0.94, 0.49, 1.42, 0.2 ,
       0.68, 1.96, 1.12, 0.8 , 0.85, 1.21, 2.44, 2.26, 1.14, 1.89, 0.31,
       0.06, 1.07, 0.41])

In [288]:
y_hat = data['latency_pred'].values
y_hat

array([2.4888635 , 0.48826516, 0.9309422 , 1.061628  , 0.8196467 ,
       0.49261189, 0.7921686 , 0.88242006, 1.1601468 , 0.36275733,
       0.8674686 , 0.961465  , 0.6638267 , 0.40813863, 0.39843118,
       0.6143881 , 1.4676718 , 1.1679631 , 1.1207069 , 0.2473098 ,
       0.23394537, 0.18397391, 1.2577022 , 1.0170275 , 1.1276613 ,
       1.191578  , 0.9024142 , 0.11868835, 0.9672638 , 0.6110817 ,
       0.17260742, 1.1529206 , 0.42975926, 0.9646293 , 1.205774  ,
       0.0339303 , 1.0693284 , 0.23420823, 2.3376565 , 1.0458857 ,
       0.71694016, 0.31065834, 0.78859067, 0.36313593, 1.2846214 ,
       0.6578646 , 2.5964231 , 1.3108565 , 1.3520206 , 0.8444942 ,
       0.7475821 , 0.37735236, 0.71026146, 1.1155001 , 0.8627765 ,
       0.64402103, 0.8625984 , 1.1830331 , 0.8179724 , 1.5967647 ,
       0.7885654 , 1.0265604 , 1.0052754 , 0.45508647, 1.523527  ,
       0.18332613, 0.71137476, 1.7175158 , 0.8795042 , 1.0714923 ,
       1.0676185 , 1.1860782 , 2.6192908 , 2.3683414 , 1.09271

In [289]:
from sklearn import metrics

In [290]:
MAE = metrics.mean_absolute_error(y, y_hat)
RMSE = metrics.mean_squared_error(y, y_hat) ** 0.5
MAPE = metrics.mean_absolute_percentage_error(y, y_hat)
print('MAE: ', MAE)
print('RMSE: ', RMSE)
print('MAPE: ', MAPE)

MAE:  0.1283142071875
RMSE:  0.2496037791682217
MAPE:  0.12628273082676367


# MLP2(send rates, block size) = throughput

In [291]:
# Split training set and test set
Xtrain2, Xtest2, Ytrain2, Ytest2 = train_test_split(X, Y2, test_size=0.2, random_state=1)

In [292]:
Xtest2

array([[200.6, 190. ],
       [ 70.3,  60. ],
       [170.6,  90. ],
       [170.7, 200. ],
       [ 90.3, 130. ],
       [180.6,  30. ],
       [100.4, 180. ],
       [150.3, 120. ],
       [ 20.1, 100. ],
       [150.7,  50. ],
       [ 90.2, 150. ],
       [187.7, 130. ],
       [100.4,  90. ],
       [170.6,  50. ],
       [169.5,  20. ],
       [120.4,  80. ],
       [190.5, 120. ],
       [ 10. ,  60. ],
       [ 40.2, 190. ],
       [120.4,  40. ],
       [ 70.4,  30. ],
       [130.6,  30. ],
       [200.6,  30. ],
       [110.5, 150. ],
       [ 10. , 180. ],
       [ 50.2, 130. ],
       [190.5,  70. ],
       [110.4,  20. ],
       [189.9,  20. ],
       [110.2,  80. ],
       [ 50.2,  20. ],
       [ 10. ,  50. ],
       [ 90.4,  60. ],
       [140.4, 160. ],
       [ 10. ,  70. ],
       [ 50.2,  10. ],
       [ 30.1, 190. ],
       [ 60.3,  30. ],
       [199.8, 180. ],
       [ 70.3, 200. ],
       [140.5,  90. ],
       [110.4,  50. ],
       [ 90.4, 120. ],
       [ 40

In [293]:
Ytest2

array([[160.4],
       [ 63.3],
       [124.9],
       [160.4],
       [ 81.6],
       [131.3],
       [ 97.1],
       [117.7],
       [ 20. ],
       [118.7],
       [ 81.1],
       [162.5],
       [ 83.4],
       [129.8],
       [126.2],
       [ 98.8],
       [135.4],
       [ 10. ],
       [ 37.3],
       [ 99.2],
       [ 61.8],
       [103.4],
       [140.4],
       [ 96.2],
       [  9.9],
       [ 48.2],
       [135.2],
       [110. ],
       [135.9],
       [ 92.4],
       [ 50.1],
       [  9.9],
       [ 78.3],
       [122.1],
       [  9.8],
       [ 50.1],
       [ 28.8],
       [ 54. ],
       [157.2],
       [ 69.9],
       [109.2],
       [109.6],
       [ 77.9],
       [ 37.3],
       [139.4],
       [ 47. ],
       [134.6],
       [119.5],
       [119.5],
       [122.1],
       [ 38.3],
       [ 99.1],
       [118.9],
       [  9.9],
       [120.4],
       [116.4],
       [121.3],
       [ 59.3],
       [121. ],
       [135.1],
       [ 55.2],
       [ 38.3],
       [

In [294]:
# property scaling
min_max_scaler2 = preprocessing.MinMaxScaler()

In [295]:
# Scaling training set data
Xtrain2_minmax = min_max_scaler2.fit_transform(Xtrain2)
Xtrain2_minmax

array([[0.21058146, 0.68421053],
       [0.05290728, 0.15789474],
       [0.73598743, 1.        ],
       [0.        , 0.68421053],
       [0.21058146, 0.52631579],
       [0.15819801, 0.05263158],
       [0.99738083, 0.05263158],
       [0.52592981, 0.68421053],
       [0.99685699, 0.57894737],
       [0.31587218, 0.36842105],
       [0.36877947, 1.        ],
       [0.89313777, 0.78947368],
       [0.73598743, 0.15789474],
       [0.83970665, 0.94736842],
       [0.42116291, 0.05263158],
       [0.78837087, 0.        ],
       [0.68412782, 0.89473684],
       [0.73493976, 0.47368421],
       [0.68360398, 0.        ],
       [0.42063908, 0.68421053],
       [0.21058146, 0.10526316],
       [0.94342588, 0.36842105],
       [0.42063908, 1.        ],
       [0.05290728, 0.36842105],
       [0.21058146, 0.47368421],
       [0.78837087, 0.57894737],
       [0.15819801, 0.68421053],
       [0.57726558, 0.68421053],
       [0.73546359, 0.94736842],
       [0.6291252 , 0.52631579],
       [0.

In [296]:
# Apply the same scaling to the test set data
Xtest2_minmax = min_max_scaler2.transform(Xtest2)
Xtest2_minmax

array([[0.9984285 , 0.94736842],
       [0.31587218, 0.26315789],
       [0.84127816, 0.42105263],
       [0.84180199, 1.        ],
       [0.42063908, 0.63157895],
       [0.8936616 , 0.10526316],
       [0.47354636, 0.89473684],
       [0.73493976, 0.57894737],
       [0.05290728, 0.47368421],
       [0.7370351 , 0.21052632],
       [0.42011524, 0.73684211],
       [0.93085385, 0.63157895],
       [0.47354636, 0.42105263],
       [0.84127816, 0.21052632],
       [0.83551598, 0.05263158],
       [0.57831325, 0.36842105],
       [0.94552122, 0.57894737],
       [0.        , 0.26315789],
       [0.15819801, 0.94736842],
       [0.57831325, 0.15789474],
       [0.31639602, 0.10526316],
       [0.63174437, 0.10526316],
       [0.9984285 , 0.10526316],
       [0.52645364, 0.73684211],
       [0.        , 0.89473684],
       [0.21058146, 0.63157895],
       [0.94552122, 0.31578947],
       [0.52592981, 0.05263158],
       [0.94237821, 0.05263158],
       [0.52488214, 0.36842105],
       [0.

In [297]:
Xtest2_tensor = torch.from_numpy(Xtest2_minmax).type(torch.float32)
Ytest2_tensor = torch.from_numpy(Ytest2).type(torch.float32)

In [298]:
train_dataset = BlockChainDataset(Xtrain2_minmax, Ytrain2)
train_loader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=False)

In [299]:
# design model using class
class Thr(torch.nn.Module):
    def __init__(self):
        super(Thr, self).__init__()
        self.fc1 = nn.Linear(2, 64)
        self.fc2 = nn.Linear(64, 8)
        self.relu = nn.ReLU()
        self.fc3 = nn.Linear(8, 1)
        self.dropout = nn.Dropout(p=0.5)
        
    def forward(self, x):
        out = self.fc1(x)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.dropout(out)
        out = self.relu(out)
        out = self.fc3(out)
        return out
    
    
model1 = Thr()

In [300]:
# construct loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model1.parameters(), lr=0.001)

In [301]:
# traning cycle forward, backward, update
def train1(epoch):
    train_loss = 0.0
    for batch_idx, (inputs, labels) in enumerate(train_loader, 0):
        y_pred = model1(inputs)
        loss = criterion(y_pred, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        train_loss += loss.item() * labels.shape[0]
    if (epoch + 1) % 10 == 0:
        print('epoch:', epoch + 1, 'train_loss:', train_loss / len(Xtrain2))
        

def test1():
    with torch.no_grad():
        y_pred = model1(Xtest2_tensor)
        loss = criterion(y_pred, Ytest2_tensor)
        print('test_loss:', loss)

In [316]:
if __name__ == '__main__':
    for epoch in range(10000):
        train1(epoch)
        if (epoch + 1) % 10 == 0:
            model1.eval()
            test1()

epoch: 10 train_loss: 82.28491439819337
test_loss: tensor(85.7236)
epoch: 20 train_loss: 82.28492431640625
test_loss: tensor(85.7235)
epoch: 30 train_loss: 82.28492317199706
test_loss: tensor(85.7236)
epoch: 40 train_loss: 82.28492736816406
test_loss: tensor(85.7236)
epoch: 50 train_loss: 82.28490333557129
test_loss: tensor(85.7236)
epoch: 60 train_loss: 82.28489685058594
test_loss: tensor(85.7236)
epoch: 70 train_loss: 82.28491020202637
test_loss: tensor(85.7236)
epoch: 80 train_loss: 82.2849277496338
test_loss: tensor(85.7236)
epoch: 90 train_loss: 82.28492889404296
test_loss: tensor(85.7235)
epoch: 100 train_loss: 82.28492469787598
test_loss: tensor(85.7234)
epoch: 110 train_loss: 82.28492088317871
test_loss: tensor(85.7236)
epoch: 120 train_loss: 82.28490409851074
test_loss: tensor(85.7236)
epoch: 130 train_loss: 82.28491172790527
test_loss: tensor(85.7236)
epoch: 140 train_loss: 82.28493728637696
test_loss: tensor(85.7235)
epoch: 150 train_loss: 82.28489608764649
test_loss: tensor

epoch: 1220 train_loss: 82.28479461669922
test_loss: tensor(85.7237)
epoch: 1230 train_loss: 82.28480262756348
test_loss: tensor(85.7236)
epoch: 1240 train_loss: 82.2848129272461
test_loss: tensor(85.7236)
epoch: 1250 train_loss: 82.2847999572754
test_loss: tensor(85.7236)
epoch: 1260 train_loss: 82.28480949401856
test_loss: tensor(85.7236)
epoch: 1270 train_loss: 82.28481979370117
test_loss: tensor(85.7236)
epoch: 1280 train_loss: 82.28480377197266
test_loss: tensor(85.7235)
epoch: 1290 train_loss: 82.28480262756348
test_loss: tensor(85.7236)
epoch: 1300 train_loss: 82.28480529785156
test_loss: tensor(85.7236)
epoch: 1310 train_loss: 82.28481788635254
test_loss: tensor(85.7236)
epoch: 1320 train_loss: 82.28480682373046
test_loss: tensor(85.7236)
epoch: 1330 train_loss: 82.28480377197266
test_loss: tensor(85.7236)
epoch: 1340 train_loss: 82.28475303649903
test_loss: tensor(85.7238)
epoch: 1350 train_loss: 82.28479232788087
test_loss: tensor(85.7236)
epoch: 1360 train_loss: 82.284802246

epoch: 2420 train_loss: 82.28471794128419
test_loss: tensor(85.7235)
epoch: 2430 train_loss: 82.28470153808594
test_loss: tensor(85.7235)
epoch: 2440 train_loss: 82.28470115661621
test_loss: tensor(85.7235)
epoch: 2450 train_loss: 82.28471336364746
test_loss: tensor(85.7235)
epoch: 2460 train_loss: 82.28470230102539
test_loss: tensor(85.7235)
epoch: 2470 train_loss: 82.28470573425292
test_loss: tensor(85.7235)
epoch: 2480 train_loss: 82.28471183776855
test_loss: tensor(85.7236)
epoch: 2490 train_loss: 82.28470878601074
test_loss: tensor(85.7236)
epoch: 2500 train_loss: 82.28471412658692
test_loss: tensor(85.7235)
epoch: 2510 train_loss: 82.28467636108398
test_loss: tensor(85.7235)
epoch: 2520 train_loss: 82.28469734191894
test_loss: tensor(85.7234)
epoch: 2530 train_loss: 82.28470573425292
test_loss: tensor(85.7235)
epoch: 2540 train_loss: 82.28470268249512
test_loss: tensor(85.7236)
epoch: 2550 train_loss: 82.28471565246582
test_loss: tensor(85.7235)
epoch: 2560 train_loss: 82.2846984

epoch: 3640 train_loss: 82.28458404541016
test_loss: tensor(85.7236)
epoch: 3650 train_loss: 82.28460121154785
test_loss: tensor(85.7235)
epoch: 3660 train_loss: 82.28460273742675
test_loss: tensor(85.7235)
epoch: 3670 train_loss: 82.28460311889648
test_loss: tensor(85.7235)
epoch: 3680 train_loss: 82.28458862304687
test_loss: tensor(85.7236)
epoch: 3690 train_loss: 82.28454322814942
test_loss: tensor(85.7239)
epoch: 3700 train_loss: 82.28460884094238
test_loss: tensor(85.7235)
epoch: 3710 train_loss: 82.28459663391114
test_loss: tensor(85.7236)
epoch: 3720 train_loss: 82.28459014892579
test_loss: tensor(85.7235)
epoch: 3730 train_loss: 82.28459358215332
test_loss: tensor(85.7236)
epoch: 3740 train_loss: 82.2845848083496
test_loss: tensor(85.7236)
epoch: 3750 train_loss: 82.28459281921387
test_loss: tensor(85.7235)
epoch: 3760 train_loss: 82.28459243774414
test_loss: tensor(85.7235)
epoch: 3770 train_loss: 82.28458251953126
test_loss: tensor(85.7235)
epoch: 3780 train_loss: 82.28459129

epoch: 4860 train_loss: 82.28451995849609
test_loss: tensor(85.7235)
epoch: 4870 train_loss: 82.28449478149415
test_loss: tensor(85.7235)
epoch: 4880 train_loss: 82.28448867797852
test_loss: tensor(85.7235)
epoch: 4890 train_loss: 82.28449020385742
test_loss: tensor(85.7236)
epoch: 4900 train_loss: 82.28448486328125
test_loss: tensor(85.7235)
epoch: 4910 train_loss: 82.28448143005372
test_loss: tensor(85.7236)
epoch: 4920 train_loss: 82.28447341918945
test_loss: tensor(85.7235)
epoch: 4930 train_loss: 82.28449172973633
test_loss: tensor(85.7235)
epoch: 4940 train_loss: 82.28446960449219
test_loss: tensor(85.7236)
epoch: 4950 train_loss: 82.28447608947754
test_loss: tensor(85.7236)
epoch: 4960 train_loss: 82.28448638916015
test_loss: tensor(85.7236)
epoch: 4970 train_loss: 82.28450012207031
test_loss: tensor(85.7235)
epoch: 4980 train_loss: 82.28446464538574
test_loss: tensor(85.7235)
epoch: 4990 train_loss: 82.28447875976562
test_loss: tensor(85.7236)
epoch: 5000 train_loss: 82.2844635

epoch: 6090 train_loss: 82.28440704345704
test_loss: tensor(85.7234)
epoch: 6100 train_loss: 82.28437843322754
test_loss: tensor(85.7235)
epoch: 6110 train_loss: 82.28438262939453
test_loss: tensor(85.7235)
epoch: 6120 train_loss: 82.28438377380371
test_loss: tensor(85.7235)
epoch: 6130 train_loss: 82.28440017700196
test_loss: tensor(85.7234)
epoch: 6140 train_loss: 82.28436889648438
test_loss: tensor(85.7235)
epoch: 6150 train_loss: 82.28436279296875
test_loss: tensor(85.7236)
epoch: 6160 train_loss: 82.28438186645508
test_loss: tensor(85.7236)
epoch: 6170 train_loss: 82.28437194824218
test_loss: tensor(85.7235)
epoch: 6180 train_loss: 82.28436584472657
test_loss: tensor(85.7235)
epoch: 6190 train_loss: 82.28435859680175
test_loss: tensor(85.7235)
epoch: 6200 train_loss: 82.28439254760742
test_loss: tensor(85.7235)
epoch: 6210 train_loss: 82.28437309265136
test_loss: tensor(85.7235)
epoch: 6220 train_loss: 82.28436813354492
test_loss: tensor(85.7235)
epoch: 6230 train_loss: 82.2843574

epoch: 7320 train_loss: 82.28426246643066
test_loss: tensor(85.7235)
epoch: 7330 train_loss: 82.28427162170411
test_loss: tensor(85.7235)
epoch: 7340 train_loss: 82.28427124023438
test_loss: tensor(85.7235)
epoch: 7350 train_loss: 82.28427352905274
test_loss: tensor(85.7231)
epoch: 7360 train_loss: 82.28427314758301
test_loss: tensor(85.7235)
epoch: 7370 train_loss: 82.28425445556641
test_loss: tensor(85.7236)
epoch: 7380 train_loss: 82.28425636291504
test_loss: tensor(85.7236)
epoch: 7390 train_loss: 82.28426055908203
test_loss: tensor(85.7235)
epoch: 7400 train_loss: 82.28427162170411
test_loss: tensor(85.7235)
epoch: 7410 train_loss: 82.2841251373291
test_loss: tensor(85.7240)
epoch: 7420 train_loss: 82.28425827026368
test_loss: tensor(85.7234)
epoch: 7430 train_loss: 82.2842945098877
test_loss: tensor(85.7234)
epoch: 7440 train_loss: 82.28424835205078
test_loss: tensor(85.7234)
epoch: 7450 train_loss: 82.28424644470215
test_loss: tensor(85.7235)
epoch: 7460 train_loss: 82.284252166

epoch: 8520 train_loss: 82.28417434692383
test_loss: tensor(85.7235)
epoch: 8530 train_loss: 82.28416519165039
test_loss: tensor(85.7236)
epoch: 8540 train_loss: 82.28417358398437
test_loss: tensor(85.7234)
epoch: 8550 train_loss: 82.28416481018067
test_loss: tensor(85.7235)
epoch: 8560 train_loss: 82.28417282104492
test_loss: tensor(85.7235)
epoch: 8570 train_loss: 82.28415870666504
test_loss: tensor(85.7235)
epoch: 8580 train_loss: 82.28416442871094
test_loss: tensor(85.7235)
epoch: 8590 train_loss: 82.28416213989257
test_loss: tensor(85.7235)
epoch: 8600 train_loss: 82.28416595458984
test_loss: tensor(85.7235)
epoch: 8610 train_loss: 82.28415222167969
test_loss: tensor(85.7235)
epoch: 8620 train_loss: 82.28415756225586
test_loss: tensor(85.7236)
epoch: 8630 train_loss: 82.28414115905761
test_loss: tensor(85.7235)
epoch: 8640 train_loss: 82.28417053222657
test_loss: tensor(85.7235)
epoch: 8650 train_loss: 82.28416519165039
test_loss: tensor(85.7233)
epoch: 8660 train_loss: 82.2841484

epoch: 9740 train_loss: 82.28406295776367
test_loss: tensor(85.7235)
epoch: 9750 train_loss: 82.28405838012695
test_loss: tensor(85.7235)
epoch: 9760 train_loss: 82.28405113220215
test_loss: tensor(85.7234)
epoch: 9770 train_loss: 82.28404273986817
test_loss: tensor(85.7235)
epoch: 9780 train_loss: 82.28403282165527
test_loss: tensor(85.7235)
epoch: 9790 train_loss: 82.28405532836913
test_loss: tensor(85.7235)
epoch: 9800 train_loss: 82.2840503692627
test_loss: tensor(85.7235)
epoch: 9810 train_loss: 82.28406257629395
test_loss: tensor(85.7235)
epoch: 9820 train_loss: 82.2840560913086
test_loss: tensor(85.7235)
epoch: 9830 train_loss: 82.2840503692627
test_loss: tensor(85.7235)
epoch: 9840 train_loss: 82.28404426574707
test_loss: tensor(85.7235)
epoch: 9850 train_loss: 82.28404006958007
test_loss: tensor(85.7234)
epoch: 9860 train_loss: 82.28404006958007
test_loss: tensor(85.7234)
epoch: 9870 train_loss: 82.28404579162597
test_loss: tensor(85.7234)
epoch: 9880 train_loss: 82.2840389251

In [317]:
with torch.no_grad():
    y_pred = model1(Xtest2_tensor)
y = pd.concat([pd.Series(Xtest2[:, 0].reshape(-1), name='send rates'), pd.Series(Xtest2[:, 1].reshape(-1), name='block size'), 
               pd.Series(Ytest2_tensor.numpy().reshape(-1), name='throughput_true'), 
               pd.Series(y_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.to_csv('../../Data/Result/Related3/throughput_true_pred_related3.csv')

In [318]:
# Compute the test set MAE RMSE MAPE
import pandas as pd

data = pd.read_csv('../../Data/Result/Related3/throughput_true_pred_related3.csv')
data.drop('Unnamed: 0', axis=1, inplace=True)
data.head()

send rates  block size  throughput_true  throughput_pred
0       200.6       190.0            160.4        161.16898
1        70.3        60.0             63.3         61.12558
2       170.6        90.0            124.9        136.47790
3       170.7       200.0            160.4        139.15407
4        90.3       130.0             81.6         77.66512

In [319]:
y = data['throughput_true'].values
y

array([160.4,  63.3, 124.9, 160.4,  81.6, 131.3,  97.1, 117.7,  20. ,
       118.7,  81.1, 162.5,  83.4, 129.8, 126.2,  98.8, 135.4,  10. ,
        37.3,  99.2,  61.8, 103.4, 140.4,  96.2,   9.9,  48.2, 135.2,
       110. , 135.9,  92.4,  50.1,   9.9,  78.3, 122.1,   9.8,  50.1,
        28.8,  54. , 157.2,  69.9, 109.2, 109.6,  77.9,  37.3, 139.4,
        47. , 134.6, 119.5, 119.5, 122.1,  38.3,  99.1, 118.9,   9.9,
       120.4, 116.4, 121.3,  59.3, 121. , 135.1,  55.2,  38.3,  96.6,
       104.2, 158.9,  96.9,  54.3, 118.1, 109.4, 122. ,  96.6,  48.6,
       125.5, 135.2,   9.9, 128.2,  30.1, 100.1,  61.5,  99.8])

In [320]:
y_hat = data['throughput_pred'].values
y_hat

array([161.16898 ,  61.12558 , 136.4779  , 139.15407 ,  77.66512 ,
       142.50072 ,  86.3641  , 122.0803  ,  24.713081, 120.72233 ,
        78.06376 , 150.14973 ,  84.235405, 135.53183 , 134.00365 ,
        98.88279 , 151.99696 ,  16.250626,  41.8001  ,  97.93671 ,
        60.490433, 105.29097 , 157.38463 ,  93.170906,  19.088888,
        47.82291 , 150.81435 ,  90.02171 , 149.18523 ,  91.29201 ,
        45.221176,  16.014105,  76.08389 , 115.658875,  16.487146,
        44.984653,  34.28373 ,  52.974064, 160.3371  ,  64.43689 ,
       114.07763 ,  90.73128 ,  77.50302 ,  38.01575 , 157.94536 ,
        46.167263, 150.48204 , 128.72502 , 129.78532 , 116.36843 ,
        38.725315,  98.335335,  99.35583 ,  19.325409, 123.41176 ,
       120.97213 , 114.94929 ,  56.521893, 109.00089 , 149.32079 ,
        54.082256,  39.198357, 100.538445, 106.16264 , 144.96687 ,
        97.77461 ,  53.920155, 129.21132 , 114.47626 , 129.75877 ,
        94.04258 ,  48.532475, 143.49986 , 156.5579  ,  17.669

In [321]:
from sklearn import metrics

In [322]:
MAE = metrics.mean_absolute_error(y, y_hat)
RMSE = metrics.mean_squared_error(y, y_hat) ** 0.5
MAPE = metrics.mean_absolute_percentage_error(y, y_hat)
print('MAE: ', MAE)
print('RMSE: ', RMSE)
print('MAPE: ', MAPE)

MAE:  6.8966246249999985
RMSE:  9.258698981420968
MAPE:  0.11773896126117259


# Choose the optimal block size

## MLP1 to predict latency

In [323]:
TPS = []
for i in range(10,210,10):
    for j in range(20):
        TPS.append(i)
TPS

[10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 20,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 30,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 40,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 80,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 90,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100,
 100

In [324]:
BS = list(range(10, 210, 10)) * 20
BS

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 

In [325]:
len(BS)

400

In [326]:
XpBS = {"Xp": TPS, "BS": BS}
XpBS

{'Xp': [10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  20,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  30,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  40,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  50,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  60,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  70,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  80,
  90,
  90,
  90,
  90,
  90,
  90

In [327]:
XpBS = pd.DataFrame(XpBS)
XpBS

Xp   BS
0     10   10
1     10   20
2     10   30
3     10   40
4     10   50
..   ...  ...
395  200  160
396  200  170
397  200  180
398  200  190
399  200  200

[400 rows x 2 columns]

In [328]:
XpBS_values = XpBS.values
XpBS_values

array([[ 10,  10],
       [ 10,  20],
       [ 10,  30],
       [ 10,  40],
       [ 10,  50],
       [ 10,  60],
       [ 10,  70],
       [ 10,  80],
       [ 10,  90],
       [ 10, 100],
       [ 10, 110],
       [ 10, 120],
       [ 10, 130],
       [ 10, 140],
       [ 10, 150],
       [ 10, 160],
       [ 10, 170],
       [ 10, 180],
       [ 10, 190],
       [ 10, 200],
       [ 20,  10],
       [ 20,  20],
       [ 20,  30],
       [ 20,  40],
       [ 20,  50],
       [ 20,  60],
       [ 20,  70],
       [ 20,  80],
       [ 20,  90],
       [ 20, 100],
       [ 20, 110],
       [ 20, 120],
       [ 20, 130],
       [ 20, 140],
       [ 20, 150],
       [ 20, 160],
       [ 20, 170],
       [ 20, 180],
       [ 20, 190],
       [ 20, 200],
       [ 30,  10],
       [ 30,  20],
       [ 30,  30],
       [ 30,  40],
       [ 30,  50],
       [ 30,  60],
       [ 30,  70],
       [ 30,  80],
       [ 30,  90],
       [ 30, 100],
       [ 30, 110],
       [ 30, 120],
       [ 30,

In [329]:
# Normalization
XpBS_minmax = min_max_scaler1.transform(XpBS_values)
XpBS_minmax

array([[0.        , 0.        ],
       [0.        , 0.05263158],
       [0.        , 0.10526316],
       [0.        , 0.15789474],
       [0.        , 0.21052632],
       [0.        , 0.26315789],
       [0.        , 0.31578947],
       [0.        , 0.36842105],
       [0.        , 0.42105263],
       [0.        , 0.47368421],
       [0.        , 0.52631579],
       [0.        , 0.57894737],
       [0.        , 0.63157895],
       [0.        , 0.68421053],
       [0.        , 0.73684211],
       [0.        , 0.78947368],
       [0.        , 0.84210526],
       [0.        , 0.89473684],
       [0.        , 0.94736842],
       [0.        , 1.        ],
       [0.05238345, 0.        ],
       [0.05238345, 0.05263158],
       [0.05238345, 0.10526316],
       [0.05238345, 0.15789474],
       [0.05238345, 0.21052632],
       [0.05238345, 0.26315789],
       [0.05238345, 0.31578947],
       [0.05238345, 0.36842105],
       [0.05238345, 0.42105263],
       [0.05238345, 0.47368421],
       [0.

In [330]:
XpBS_tensor = torch.from_numpy(XpBS_minmax).type(torch.float32)

In [331]:
with torch.no_grad():
    latency_pred = model(XpBS_tensor)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(latency_pred.numpy().reshape(-1), name='latency_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related3/latency_pred_related3.csv')

In [332]:
y

send rates  block size  latency_pred
0            10          10      0.263789
1            10          20      0.761386
2            10          30      1.080978
3            10          40      1.097761
4            10          50      1.152921
..          ...         ...           ...
395         200         160      2.706232
396         200         170      2.351660
397         200         180      2.354682
398         200         190      2.437658
399         200         200      2.620018

[400 rows x 3 columns]

## MLP2 to predict throughput

In [333]:
# Normalization
XpBS_minmax2 = min_max_scaler2.transform(XpBS_values)
XpBS_minmax2

array([[0.        , 0.        ],
       [0.        , 0.05263158],
       [0.        , 0.10526316],
       [0.        , 0.15789474],
       [0.        , 0.21052632],
       [0.        , 0.26315789],
       [0.        , 0.31578947],
       [0.        , 0.36842105],
       [0.        , 0.42105263],
       [0.        , 0.47368421],
       [0.        , 0.52631579],
       [0.        , 0.57894737],
       [0.        , 0.63157895],
       [0.        , 0.68421053],
       [0.        , 0.73684211],
       [0.        , 0.78947368],
       [0.        , 0.84210526],
       [0.        , 0.89473684],
       [0.        , 0.94736842],
       [0.        , 1.        ],
       [0.05238345, 0.        ],
       [0.05238345, 0.05263158],
       [0.05238345, 0.10526316],
       [0.05238345, 0.15789474],
       [0.05238345, 0.21052632],
       [0.05238345, 0.26315789],
       [0.05238345, 0.31578947],
       [0.05238345, 0.36842105],
       [0.05238345, 0.42105263],
       [0.05238345, 0.47368421],
       [0.

In [334]:
XpBS_tensor2 = torch.from_numpy(XpBS_minmax2).type(torch.float32)

In [335]:
with torch.no_grad():
    throughput_pred = model1(XpBS_tensor2)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(throughput_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related3/throughput_pred_related3.csv')

In [336]:
y

send rates  block size  throughput_pred
0            10          10        15.068465
1            10          20        15.304539
2            10          30        15.541059
3            10          40        15.777582
4            10          50        16.014105
..          ...         ...              ...
395         200         160       160.012894
396         200         170       160.249405
397         200         180       160.485947
398         200         190       160.722458
399         200         200       160.958969

[400 rows x 3 columns]

In [337]:
with torch.no_grad():
    latency_pred = model(XpBS_tensor)
    throughput_pred = model1(XpBS_tensor2)
y = pd.concat([pd.Series(XpBS_values[:, 0].reshape(-1), name='send rates'), pd.Series(XpBS_values[:, 1].reshape(-1), name='block size'), 
               pd.Series(latency_pred.numpy().reshape(-1), name='latency_pred'),
               pd.Series(throughput_pred.numpy().reshape(-1), name='throughput_pred')], axis=1)
y.index = XpBS.index
y.to_csv('../../Data/Result/Related3/latency_throughput_pred_related3.csv')

## Set the score function to chose the best block

In [338]:
y

send rates  block size  latency_pred  throughput_pred
0            10          10      0.263789        15.068465
1            10          20      0.761386        15.304539
2            10          30      1.080978        15.541059
3            10          40      1.097761        15.777582
4            10          50      1.152921        16.014105
..          ...         ...           ...              ...
395         200         160      2.706232       160.012894
396         200         170      2.351660       160.249405
397         200         180      2.354682       160.485947
398         200         190      2.437658       160.722458
399         200         200      2.620018       160.958969

[400 rows x 4 columns]

In [339]:
for name, group in y.groupby('send rates', sort=False):
    print(name)
    print(group)

10
    send rates  block size  latency_pred  throughput_pred
0           10          10      0.263789        15.068465
1           10          20      0.761386        15.304539
2           10          30      1.080978        15.541059
3           10          40      1.097761        15.777582
4           10          50      1.152921        16.014105
5           10          60      1.167963        16.250626
6           10          70      1.205774        16.487146
7           10          80      1.114404        16.723669
8           10          90      1.144804        16.960192
9           10         100      1.132989        17.196712
10          10         110      1.089252        17.433235
11          10         120      1.092720        17.669756
12          10         130      1.096455        17.906279
13          10         140      1.093285        18.142801
14          10         150      1.089604        18.379322
15          10         160      1.081395        18.615845
16         

In [340]:
la_max_min = y.groupby('send rates', sort=False)['latency_pred'].agg(['max', 'min'])
la_max_min

max       min
send rates                    
10          1.205774  0.263789
20          1.160087  0.155900
30          1.132952  0.118345
40          1.118886  0.074766
50          1.198437  0.035269
60          1.228073  0.049518
70          1.118488  0.063975
80          0.956646  0.050968
90          0.883040  0.051824
100         0.882315  0.062724
110         1.114442  0.073622
120         1.459007  0.084523
130         1.018586  0.098502
140         0.984429  0.118054
150         1.317163  0.141362
160         1.868159  0.208175
170         2.708397  0.212505
180         2.855116  0.378550
190         2.880932  0.875724
200         2.815543  1.238566

In [341]:
la_col=['latency_max', 'latency_min']
la_max_min.columns = la_col
la_max_min

latency_max  latency_min
send rates                          
10             1.205774     0.263789
20             1.160087     0.155900
30             1.132952     0.118345
40             1.118886     0.074766
50             1.198437     0.035269
60             1.228073     0.049518
70             1.118488     0.063975
80             0.956646     0.050968
90             0.883040     0.051824
100            0.882315     0.062724
110            1.114442     0.073622
120            1.459007     0.084523
130            1.018586     0.098502
140            0.984429     0.118054
150            1.317163     0.141362
160            1.868159     0.208175
170            2.708397     0.212505
180            2.855116     0.378550
190            2.880932     0.875724
200            2.815543     1.238566

In [342]:
th_max_min = y.groupby('send rates', sort=False)['throughput_pred'].agg(['max', 'min'])
th_max_min

max         min
send rates                        
10           19.562485   15.068465
20           27.003880   22.509968
30           34.445827   29.951918
40           41.887779   37.393864
50           49.329731   44.835815
60           56.771679   52.277767
70           64.213623   59.719715
80           71.655579   67.161659
90           79.097519   74.603607
100          86.539467   82.045555
110          93.981430   89.487511
120         101.423363   96.929436
130         108.865326  104.371407
140         116.307259  111.813362
150         123.749222  119.255318
160         131.191177  126.697258
170         138.633118  134.139221
180         146.075073  141.581161
190         153.517029  149.023117
200         160.958969  156.465073

In [343]:
th_col=['throughput_max', 'throughput_min']
th_max_min.columns = th_col
th_max_min

throughput_max  throughput_min
send rates                                
10               19.562485       15.068465
20               27.003880       22.509968
30               34.445827       29.951918
40               41.887779       37.393864
50               49.329731       44.835815
60               56.771679       52.277767
70               64.213623       59.719715
80               71.655579       67.161659
90               79.097519       74.603607
100              86.539467       82.045555
110              93.981430       89.487511
120             101.423363       96.929436
130             108.865326      104.371407
140             116.307259      111.813362
150             123.749222      119.255318
160             131.191177      126.697258
170             138.633118      134.139221
180             146.075073      141.581161
190             153.517029      149.023117
200             160.958969      156.465073

In [344]:
# Restore the grouping index to the column
la_max_min.reset_index(inplace=True)
la_max_min

send rates  latency_max  latency_min
0           10     1.205774     0.263789
1           20     1.160087     0.155900
2           30     1.132952     0.118345
3           40     1.118886     0.074766
4           50     1.198437     0.035269
5           60     1.228073     0.049518
6           70     1.118488     0.063975
7           80     0.956646     0.050968
8           90     0.883040     0.051824
9          100     0.882315     0.062724
10         110     1.114442     0.073622
11         120     1.459007     0.084523
12         130     1.018586     0.098502
13         140     0.984429     0.118054
14         150     1.317163     0.141362
15         160     1.868159     0.208175
16         170     2.708397     0.212505
17         180     2.855116     0.378550
18         190     2.880932     0.875724
19         200     2.815543     1.238566

In [345]:
th_max_min.reset_index(inplace=True)
th_max_min

send rates  throughput_max  throughput_min
0           10       19.562485       15.068465
1           20       27.003880       22.509968
2           30       34.445827       29.951918
3           40       41.887779       37.393864
4           50       49.329731       44.835815
5           60       56.771679       52.277767
6           70       64.213623       59.719715
7           80       71.655579       67.161659
8           90       79.097519       74.603607
9          100       86.539467       82.045555
10         110       93.981430       89.487511
11         120      101.423363       96.929436
12         130      108.865326      104.371407
13         140      116.307259      111.813362
14         150      123.749222      119.255318
15         160      131.191177      126.697258
16         170      138.633118      134.139221
17         180      146.075073      141.581161
18         190      153.517029      149.023117
19         200      160.958969      156.465073

In [346]:
la_max = la_max_min['latency_max'].values
la_max = list(la_max)
la_max
len(la_max)

20

In [347]:
la_max_all = []
for i in range(len(la_max)):
    la_max_all.extend([la_max[i]]*20)
    
la_max_all

[1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.205774,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1600865,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1329519,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1188859,
 1.1984369,
 1.1984369,
 1.1984369,
 1.1984369,
 1.1984369,


In [348]:
la_min = la_max_min['latency_min'].values
la_min = list(la_min)
la_min

[0.26378894,
 0.15589988,
 0.1183455,
 0.07476628,
 0.035268545,
 0.049518466,
 0.06397486,
 0.050967813,
 0.051823974,
 0.062723756,
 0.073622465,
 0.08452296,
 0.09850228,
 0.11805391,
 0.14136195,
 0.2081747,
 0.2125045,
 0.37855017,
 0.87572384,
 1.2385656]

In [349]:
la_min_all = []
for i in range(len(la_min)):
    la_min_all.extend([la_min[i]]*20)
    
la_min_all

[0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.26378894,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.15589988,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.1183455,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.07476628,
 0.074

In [350]:
y['latency_min'] = la_min_all
y

send rates  block size  latency_pred  throughput_pred  latency_min
0            10          10      0.263789        15.068465     0.263789
1            10          20      0.761386        15.304539     0.263789
2            10          30      1.080978        15.541059     0.263789
3            10          40      1.097761        15.777582     0.263789
4            10          50      1.152921        16.014105     0.263789
..          ...         ...           ...              ...          ...
395         200         160      2.706232       160.012894     1.238566
396         200         170      2.351660       160.249405     1.238566
397         200         180      2.354682       160.485947     1.238566
398         200         190      2.437658       160.722458     1.238566
399         200         200      2.620018       160.958969     1.238566

[400 rows x 5 columns]

In [351]:
y['latency_max'] = la_max_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.263789        15.068465     0.263789   
1            10          20      0.761386        15.304539     0.263789   
2            10          30      1.080978        15.541059     0.263789   
3            10          40      1.097761        15.777582     0.263789   
4            10          50      1.152921        16.014105     0.263789   
..          ...         ...           ...              ...          ...   
395         200         160      2.706232       160.012894     1.238566   
396         200         170      2.351660       160.249405     1.238566   
397         200         180      2.354682       160.485947     1.238566   
398         200         190      2.437658       160.722458     1.238566   
399         200         200      2.620018       160.958969     1.238566   

     latency_max  
0       1.205774  
1       1.205774  
2       1.205774  
3       1.205774  
4       1.205774  
..           ...  
395     2.815543  
396     2.815543  
397     2.815543  
398     2.815543  
399     2.815543  

[400 rows x 6 columns]

In [352]:
th_max = th_max_min['throughput_max'].values
th_max = list(th_max)
th_max

[19.562485,
 27.00388,
 34.445827,
 41.88778,
 49.32973,
 56.77168,
 64.21362,
 71.65558,
 79.09752,
 86.53947,
 93.98143,
 101.42336,
 108.865326,
 116.30726,
 123.74922,
 131.19118,
 138.63312,
 146.07507,
 153.51703,
 160.95897]

In [353]:
th_max_all = []
for i in range(len(th_max)):
    th_max_all.extend([th_max[i]] * 20)
    
th_max_all

[19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 19.562485,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 27.00388,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 34.445827,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 41.88778,
 49.32973,
 49.32973,
 49.32973,
 49.32973,
 49.32973,
 49.32973,
 49.32973,
 49

In [354]:
th_min = th_max_min['throughput_min'].values
th_min = list(th_min)
th_min

[15.068465,
 22.509968,
 29.951918,
 37.393864,
 44.835815,
 52.277767,
 59.719715,
 67.16166,
 74.60361,
 82.045555,
 89.48751,
 96.929436,
 104.37141,
 111.81336,
 119.25532,
 126.69726,
 134.13922,
 141.58116,
 149.02312,
 156.46507]

In [355]:
th_min_all = []
for i in range(len(th_min)):
    th_min_all.extend([th_min[i]] * 20)
    
th_min_all

[15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 15.068465,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 22.509968,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 29.951918,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 37.393864,
 44.835815,
 44.835815,
 44.835815,
 44.

In [356]:
y['throughput_min'] = th_min_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.263789        15.068465     0.263789   
1            10          20      0.761386        15.304539     0.263789   
2            10          30      1.080978        15.541059     0.263789   
3            10          40      1.097761        15.777582     0.263789   
4            10          50      1.152921        16.014105     0.263789   
..          ...         ...           ...              ...          ...   
395         200         160      2.706232       160.012894     1.238566   
396         200         170      2.351660       160.249405     1.238566   
397         200         180      2.354682       160.485947     1.238566   
398         200         190      2.437658       160.722458     1.238566   
399         200         200      2.620018       160.958969     1.238566   

     latency_max  throughput_min  
0       1.205774       15.068465  
1       1.205774       15.068465  
2       1.205774       15.068465  
3       1.205774       15.068465  
4       1.205774       15.068465  
..           ...             ...  
395     2.815543      156.465073  
396     2.815543      156.465073  
397     2.815543      156.465073  
398     2.815543      156.465073  
399     2.815543      156.465073  

[400 rows x 7 columns]

In [357]:
y['throughput_max'] = th_max_all
y

send rates  block size  latency_pred  throughput_pred  latency_min  \
0            10          10      0.263789        15.068465     0.263789   
1            10          20      0.761386        15.304539     0.263789   
2            10          30      1.080978        15.541059     0.263789   
3            10          40      1.097761        15.777582     0.263789   
4            10          50      1.152921        16.014105     0.263789   
..          ...         ...           ...              ...          ...   
395         200         160      2.706232       160.012894     1.238566   
396         200         170      2.351660       160.249405     1.238566   
397         200         180      2.354682       160.485947     1.238566   
398         200         190      2.437658       160.722458     1.238566   
399         200         200      2.620018       160.958969     1.238566   

     latency_max  throughput_min  throughput_max  
0       1.205774       15.068465       19.562485  
1       1.205774       15.068465       19.562485  
2       1.205774       15.068465       19.562485  
3       1.205774       15.068465       19.562485  
4       1.205774       15.068465       19.562485  
..           ...             ...             ...  
395     2.815543      156.465073      160.958969  
396     2.815543      156.465073      160.958969  
397     2.815543      156.465073      160.958969  
398     2.815543      156.465073      160.958969  
399     2.815543      156.465073      160.958969  

[400 rows x 8 columns]

In [358]:
y.to_csv('../../Data/Result/Related3/latency_throughput_pred_max_min_related3.csv')

### choose different weights

In [359]:
# Read the processed data directly
y = pd.read_csv('../../Data/Result/Related3/latency_throughput_pred_max_min_related3.csv')
y

Unnamed: 0  send rates  block size  latency_pred  throughput_pred  \
0             0          10          10      0.263789        15.068465   
1             1          10          20      0.761386        15.304539   
2             2          10          30      1.080978        15.541059   
3             3          10          40      1.097761        15.777582   
4             4          10          50      1.152921        16.014105   
..          ...         ...         ...           ...              ...   
395         395         200         160      2.706232       160.012900   
396         396         200         170      2.351660       160.249400   
397         397         200         180      2.354682       160.485950   
398         398         200         190      2.437658       160.722460   
399         399         200         200      2.620018       160.958970   

     latency_min  latency_max  throughput_min  throughput_max  
0       0.263789     1.205774       15.068465       19.562485  
1       0.263789     1.205774       15.068465       19.562485  
2       0.263789     1.205774       15.068465       19.562485  
3       0.263789     1.205774       15.068465       19.562485  
4       0.263789     1.205774       15.068465       19.562485  
..           ...          ...             ...             ...  
395     1.238566     2.815543      156.465070      160.958970  
396     1.238566     2.815543      156.465070      160.958970  
397     1.238566     2.815543      156.465070      160.958970  
398     1.238566     2.815543      156.465070      160.958970  
399     1.238566     2.815543      156.465070      160.958970  

[400 rows x 9 columns]

In [378]:
alpha = 0.1
beta = 0.9

In [379]:
latency_score = alpha * ((y['latency_max'] - y['latency_pred']) / (y['latency_max'] - y['latency_min']))

In [380]:
throughput_score = beta * ((y['throughput_pred'] - y['throughput_min']) / (y['throughput_max'] - y['throughput_min']))

In [381]:
y_score = latency_score.values + throughput_score.values
y_score

array([0.1       , 0.09445335, 0.10789287, 0.15347862, 0.19499052,
       0.24076077, 0.28411376, 0.34118122, 0.38532134, 0.43394256,
       0.48595316, 0.53295217, 0.57992315, 0.62762707, 0.67538496,
       0.72362396, 0.76801883, 0.81344691, 0.86210508, 0.91087455,
       0.1       , 0.12332625, 0.14195362, 0.1713106 , 0.20067348,
       0.244484  , 0.28768529, 0.3352688 , 0.3816156 , 0.42631516,
       0.47876544, 0.52652549, 0.57426005, 0.62199595, 0.66973126,
       0.71653811, 0.76201506, 0.81077908, 0.85935931, 0.90618526,
       0.1       , 0.13520345, 0.1614806 , 0.19100421, 0.22055195,
       0.2500996 , 0.29296387, 0.33530923, 0.38155822, 0.42631584,
       0.47560008, 0.52335341, 0.57108477, 0.61881651, 0.66654709,
       0.71199535, 0.76166244, 0.81031299, 0.85888054, 0.90390031,
       0.1       , 0.13258009, 0.16702463, 0.20276701, 0.23860265,
       0.27192007, 0.3012662 , 0.34022406, 0.38523867, 0.42832928,
       0.47398037, 0.52151144, 0.56923402, 0.61695472, 0.66418

In [382]:
y['score'] = y_score

In [383]:
y.to_csv('../../Data/Result/Related3/latency_throughput_score_alpha' + str(alpha) + '_beta' + str(beta) + '_related3.csv')

In [ ]:
y